Agent Class Reference
#include <Agent.h>
Public Member Functions
 Agent (Map *m, unsigned long id, Clock *clock)
virtual ~Agent ()
bool operator== (const Agent &a)
virtual string getName ()=0
virtual string toString ()=0
 Map * getMap () const
void setMap (Map *map)
 Clock * getClock () const
unsigned long getId () const
Private Attributes
 Map * m_map
unsigned long m_id
 Clock * m_clock
Detailed Description
Definition at line 17 of file Agent.h.
Constructor & Destructor Documentation
Agent()
Agent::Agent (Map * m, unsigned long id, Clock * clock)
Constructor of the class. Agent is the base class for all agents used in the simulator: persons, antennas, devices. Agent is an abstract class, the users should build specific subclasses
Parameters
m - the Map where the simulation take place.
id - the id of this agent, it uniquely identifies the agent
clock - the clock used by the simulator, it is the same for all agents
Definition at line 12 of file Agent.cpp.
~Agent()
Agent::~Agent () [virtual]
Default destructor of the class.
Definition at line 18 of file Agent.cpp.
Member Function Documentation
getClock()
 Clock * Agent::getClock () const
Returns a pointer to the Clock object used for simulation. All Agents use the same Clock object for a simulation.
Returns
Definition at line 33 of file Agent.cpp.
References m_clock.
Referenced by LocatableAgent::dumpLocation(), and Antenna::registerEvent().
getId()
unsigned long Agent::getId () const
Returns the id of the object.
Returns
the id of the object.
Definition at line 37 of file Agent.cpp.
References m_id.
Referenced by Grid::computeProbability(), Person::dumpDevices(), LocatableAgent::dumpLocation(), operator==(), Antenna::registerEvent(), LocatableAgent::toString(), HoldableAgent::toString(), Person::toString(), and MobilePhone::tryConnectNaiveAlgorithm().
getMap()
 Map * Agent::getMap () const
Getter that returns a pointer to the map passed to the constructor when the an object was build.
Returns
a pointer to the Map object that was passed to the constructor. All agents use the same map for a simulation.
Definition at line 25 of file Agent.cpp.
References m_map.
Referenced by Antenna::Antenna(), and Person::randomWalk().
getName()
virtual string Agent::getName () [pure virtual]
This function is used to get the name of the class. It is a pure virtual function, all subclasses implment it and return the actual name of the class.
Returns
the name of the class.
Implemented in Antenna , Person , HoldableAgent , MovableAgent , ImmovableAgent , MobilePhone , LocatableAgent , and Tablet .
operator==()
bool Agent::operator== (const Agent & a)
The equal operator for agents.
Parameters
a the object with which we test the equality
Returns
true if this object is the equal to a, flase otherwise. Thw objects are considered to be equal if they have the same id.
Definition at line 21 of file Agent.cpp.
References getId(), and m_id.
setMap()
void Agent::setMap (Map * map)
Sets the Map to be used by this agent during the simulation. It is not advisable to change the map during a simulation.
Parameters
map pointer to a Map object.
Definition at line 29 of file Agent.cpp.
References m_map.
toString()
virtual string Agent::toString () [pure virtual]
Builds a string with of the relevant information of the class. It is useful to output on the console or in a file the description of concrete agents.
Returns
a string representation of the class content. The values of the members are written in this string.
Implemented in Antenna , Person , HoldableAgent , MovableAgent , MobilePhone , LocatableAgent , ImmovableAgent , and Tablet .
Member Data Documentation
m_clock
 Clock* Agent::m_clock [private]
Definition at line 82 of file Agent.h.
Referenced by getClock().
m_id
unsigned long Agent::m_id [private]
Definition at line 81 of file Agent.h.
Referenced by getId(), and operator==().
m_map
 Map* Agent::m_map [private]
Definition at line 80 of file Agent.h.
Referenced by getMap(), and setMap().
The documentation for this class was generated from the following files:
include/ Agent.h
src/ Agent.cpp