tinyxml2::XMLComment Class Reference
#include <tinyxml2.h>
Public Member Functions
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual bool Accept (XMLVisitor *visitor) const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Protected Member Functions
 XMLComment (XMLDocument *doc)
virtual ~XMLComment ()
char * ParseDeep (char *p, StrPair *parentEndTag, int *curLineNumPtr)
Private Member Functions
 XMLComment (const XMLComment &)
 XMLComment & operator= (const XMLComment &)
Friends
class XMLDocument
Additional Inherited Members
Detailed Description
An XML Comment.
Definition at line 1024 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLComment() [1/2]
tinyxml2::XMLComment::XMLComment (XMLDocument * doc) [explicit], [protected]
Definition at line 1202 of file tinyxml2.cpp.
~XMLComment()
tinyxml2::XMLComment::~XMLComment () [protected], [virtual]
Definition at line 1207 of file tinyxml2.cpp.
XMLComment() [2/2]
tinyxml2::XMLComment::XMLComment (const XMLComment &) [private]
Member Function Documentation
Accept()
bool tinyxml2::XMLComment::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
 http://www.saxproject.org/
 http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for `visiting`.
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode .
Definition at line 1241 of file tinyxml2.cpp.
References TIXMLASSERT, and tinyxml2::XMLVisitor::Visit().
operator=()
 XMLComment& tinyxml2::XMLComment::operator= (const XMLComment &) [private]
ParseDeep()
char * tinyxml2::XMLComment::ParseDeep (char * p, StrPair * parentEndTag, int * curLineNumPtr) [protected], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1212 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_parseLineNum, tinyxml2::XMLNode::_value, tinyxml2::StrPair::COMMENT, tinyxml2::StrPair::ParseText(), tinyxml2::XMLDocument::SetError(), and tinyxml2::XML_ERROR_PARSING_COMMENT.
ShallowClone()
 XMLNode * tinyxml2::XMLComment::ShallowClone (XMLDocument * document) const [virtual]
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode .
Definition at line 1223 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLDocument::NewComment(), and tinyxml2::XMLNode::Value().
ShallowEqual()
bool tinyxml2::XMLComment::ShallowEqual (const XMLNode * compare) const [virtual]
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode .
Definition at line 1233 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, tinyxml2::XMLNode::ToComment(), and tinyxml2::XMLNode::Value().
ToComment() [1/2]
virtual XMLComment* tinyxml2::XMLComment::ToComment () [inline], [virtual]
Safely cast to a Comment, or null.
Reimplemented from tinyxml2::XMLNode .
Definition at line 1028 of file tinyxml2.h.
ToComment() [2/2]
virtual const XMLComment* tinyxml2::XMLComment::ToComment () const [inline], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1031 of file tinyxml2.h.
Friends And Related Function Documentation
XMLDocument
friend class XMLDocument [friend]
Definition at line 1026 of file tinyxml2.h.
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp