MobilePhone Class Reference
#include <MobilePhone.h>
Public Member Functions
 MobilePhone (Map *m, long id, Point *initPosition, Agent *holder, Clock *clock, double powerThreshold, double qualityThreshold, HoldableAgent::CONNECTION_TYPE connType)
virtual ~MobilePhone ()
string getName () override
string toString () override
Point * move (MovementType mvType) override
bool tryConnect (HoldableAgent::CONNECTION_TYPE type) override
double getQualityThreshold () const
void setQualityThreshold (double qualityThreshold)
double getPowerThreshold () const
void setPowerThreshold (double powerThreshold)
Private Member Functions
bool tryConnectNaiveAlgorithm (HoldableAgent::CONNECTION_TYPE type)
Private Attributes
double m_powerThreshold
double m_qualityThreshold
 Antenna * m_connectedTo
 HoldableAgent::CONNECTION_TYPE m_connType
Additional Inherited Members
Detailed Description
Definition at line 24 of file MobilePhone.h.
Constructor & Destructor Documentation
MobilePhone()
MobilePhone::MobilePhone (Map * m, long id, Point * initPosition, Agent * holder, Clock * clock, double powerThreshold, double qualityThreshold, HoldableAgent::CONNECTION_TYPE connType) [explicit]
Definition at line 18 of file MobilePhone.cpp.
References m_connectedTo, m_connType, m_qualityThreshold, Constants::POWER_THRESHOLD, and Constants::QUALITY_THRESHOLD.
~MobilePhone()
MobilePhone::~MobilePhone () [virtual]
Definition at line 24 of file MobilePhone.cpp.
Member Function Documentation
getName()
string MobilePhone::getName () [inline], [override], [virtual]
This function is used to get the name of the class. It is a pure virtual function, all subclasses implment it and return the actual name of the class.
Returns
the name of the class.
Reimplemented from HoldableAgent .
Definition at line 29 of file MobilePhone.h.
getPowerThreshold()
double MobilePhone::getPowerThreshold () const
Definition at line 96 of file MobilePhone.cpp.
References m_powerThreshold.
getQualityThreshold()
double MobilePhone::getQualityThreshold () const
Definition at line 88 of file MobilePhone.cpp.
References m_qualityThreshold.
move()
Point* MobilePhone::move (MovementType mvType) [inline], [override], [virtual]
Implements MovableAgent .
Definition at line 35 of file MobilePhone.h.
setPowerThreshold()
void MobilePhone::setPowerThreshold (double powerThreshold)
Definition at line 100 of file MobilePhone.cpp.
References m_powerThreshold.
setQualityThreshold()
void MobilePhone::setQualityThreshold (double qualityThreshold)
Definition at line 92 of file MobilePhone.cpp.
References m_qualityThreshold.
toString()
string MobilePhone::toString () [override], [virtual]
Builds a string with of the relevant information of the class. It is useful to output on the console or in a file the description of concrete agents.
Returns
a string representation of the class content. The values of the members are written in this string.
Reimplemented from HoldableAgent .
Definition at line 28 of file MobilePhone.cpp.
References HoldableAgent::toString().
tryConnect()
bool MobilePhone::tryConnect (HoldableAgent::CONNECTION_TYPE type) [override], [virtual]
Implements HoldableAgent .
Definition at line 32 of file MobilePhone.cpp.
References tryConnectNaiveAlgorithm().
tryConnectNaiveAlgorithm()
bool MobilePhone::tryConnectNaiveAlgorithm (HoldableAgent::CONNECTION_TYPE type) [private]
Definition at line 36 of file MobilePhone.cpp.
References EMField::computeMaxPower(), EMField::computeMaxQuality(), Antenna::dettachDevice(), Agent::getId(), EMField::getInRangeAntennas(), LocatableAgent::getLocation(), EMField::instance(), EMField::isAntennaInRange(), m_connectedTo, m_powerThreshold, and Constants::QUALITY_THRESHOLD.
Referenced by tryConnect().
Member Data Documentation
m_connectedTo
 Antenna* MobilePhone::m_connectedTo [private]
Definition at line 50 of file MobilePhone.h.
Referenced by MobilePhone(), and tryConnectNaiveAlgorithm().
m_connType
 HoldableAgent::CONNECTION_TYPE MobilePhone::m_connType [private]
Definition at line 51 of file MobilePhone.h.
Referenced by MobilePhone().
m_powerThreshold
double MobilePhone::m_powerThreshold [private]
Definition at line 48 of file MobilePhone.h.
Referenced by getPowerThreshold(), setPowerThreshold(), and tryConnectNaiveAlgorithm().
m_qualityThreshold
double MobilePhone::m_qualityThreshold [private]
Definition at line 49 of file MobilePhone.h.
Referenced by getQualityThreshold(), MobilePhone(), and setQualityThreshold().
The documentation for this class was generated from the following files:
include/ MobilePhone.h
src/ MobilePhone.cpp