HoldableAgent Class Reference
#include <HoldableAgent.h>
Public Types
enum CONNECTION_TYPE { USING_POWER,
 USING_SIGNAL_QUALITY,
 UNKNOWN
 }
Public Member Functions
 HoldableAgent (Map *m, long id, Point *initPosition, Agent *holder, Clock *clock)
 HoldableAgent (const HoldableAgent &h)
virtual ~HoldableAgent ()
 Agent * getHolder () const
void setHolder (Agent *holder)
string getName () override
string toString () override
virtual bool tryConnect (CONNECTION_TYPE type)=0
virtual bool isConnected () const
void setLocation (Point *location) override
vector< Antenna * > getAntennas () const
Private Attributes
 Agent * m_holder
vector< Antenna * > m_antennas
Detailed Description
Definition at line 21 of file HoldableAgent.h.
Member Enumeration Documentation
CONNECTION_TYPE
enum HoldableAgent::CONNECTION_TYPE
Enumerator
USING_POWER
USING_SIGNAL_QUALITY
UNKNOWN
Definition at line 25 of file HoldableAgent.h.
Constructor & Destructor Documentation
HoldableAgent() [1/2]
HoldableAgent::HoldableAgent (Map * m, long id, Point * initPosition, Agent * holder, Clock * clock) [explicit]
Definition at line 16 of file HoldableAgent.cpp.
HoldableAgent() [2/2]
HoldableAgent::HoldableAgent (const HoldableAgent & h)
Definition at line 22 of file HoldableAgent.cpp.
References getAntennas(), getHolder(), m_antennas, and m_holder.
~HoldableAgent()
HoldableAgent::~HoldableAgent () [virtual]
Definition at line 29 of file HoldableAgent.cpp.
Member Function Documentation
getAntennas()
vector< Antenna * > HoldableAgent::getAntennas () const
Definition at line 54 of file HoldableAgent.cpp.
References m_antennas.
Referenced by HoldableAgent().
getHolder()
 Agent * HoldableAgent::getHolder () const
Definition at line 33 of file HoldableAgent.cpp.
References m_holder.
Referenced by HoldableAgent().
getName()
string HoldableAgent::getName () [inline], [override], [virtual]
Implements Agent .
Reimplemented in MobilePhone , and Tablet .
Definition at line 34 of file HoldableAgent.h.
isConnected()
bool HoldableAgent::isConnected () const [virtual]
Definition at line 50 of file HoldableAgent.cpp.
References m_antennas.
setHolder()
void HoldableAgent::setHolder (Agent * holder)
Definition at line 37 of file HoldableAgent.cpp.
References LocatableAgent::getLocation(), m_holder, setLocation(), and MovableAgent::setSpeed().
setLocation()
void HoldableAgent::setLocation (Point * location) [override], [virtual]
Reimplemented from LocatableAgent .
Definition at line 58 of file HoldableAgent.cpp.
References LocatableAgent::setLocation(), and tryConnect().
Referenced by setHolder(), and Person::setLocation().
toString()
string HoldableAgent::toString () [override], [virtual]
Implements Agent .
Reimplemented in MobilePhone , and Tablet .
Definition at line 63 of file HoldableAgent.cpp.
References Agent::getId(), m_holder, and MovableAgent::toString().
Referenced by Tablet::toString(), and MobilePhone::toString().
tryConnect()
virtual bool HoldableAgent::tryConnect (CONNECTION_TYPE type) [pure virtual]
Implemented in MobilePhone , and Tablet .
Referenced by setLocation().
Member Data Documentation
m_antennas
vector< Antenna*> HoldableAgent::m_antennas [private]
Definition at line 47 of file HoldableAgent.h.
Referenced by getAntennas(), HoldableAgent(), and isConnected().
m_holder
 Agent* HoldableAgent::m_holder [private]
Definition at line 46 of file HoldableAgent.h.
Referenced by getHolder(), HoldableAgent(), setHolder(), and toString().
The documentation for this class was generated from the following files:
include/ HoldableAgent.h
src/ HoldableAgent.cpp