tinyxml2::XMLAttribute Class Reference
#include <tinyxml2.h>
Public Member Functions
const char * Name () const
The name of the attribute.
const char * Value () const
The value of the attribute.
int GetLineNum () const
Gets the line number the attribute is in, if the document was parsed from a file.
const XMLAttribute * Next () const
The next attribute in the list.
int IntValue () const
int64_t Int64Value () const
unsigned UnsignedValue () const
Query as an unsigned integer. See IntValue()
bool BoolValue () const
Query as a boolean. See IntValue()
double DoubleValue () const
Query as a double. See IntValue()
float FloatValue () const
Query as a float. See IntValue()
 XMLError QueryIntValue (int *value) const
 XMLError QueryUnsignedValue (unsigned int *value) const
See QueryIntValue.
 XMLError QueryInt64Value (int64_t *value) const
See QueryIntValue.
 XMLError QueryBoolValue (bool *value) const
See QueryIntValue.
 XMLError QueryDoubleValue (double *value) const
See QueryIntValue.
 XMLError QueryFloatValue (float *value) const
See QueryIntValue.
void SetAttribute (const char *value)
Set the attribute to a string value.
void SetAttribute (int value)
Set the attribute to value.
void SetAttribute (unsigned value)
Set the attribute to value.
void SetAttribute (int64_t value)
Set the attribute to value.
void SetAttribute (bool value)
Set the attribute to value.
void SetAttribute (double value)
Set the attribute to value.
void SetAttribute (float value)
Set the attribute to value.
Private Types
enum { BUF_SIZE = 200
 }
Private Member Functions
 XMLAttribute ()
virtual ~XMLAttribute ()
 XMLAttribute (const XMLAttribute &)
void operator= (const XMLAttribute &)
void SetName (const char *name)
char * ParseDeep (char *p, bool processEntities, int *curLineNumPtr)
Private Attributes
 StrPair _name
 StrPair _value
int _parseLineNum
 XMLAttribute * _next
 MemPool * _memPool
Friends
class XMLElement
Detailed Description
An attribute is a name-value pair. Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not XMLNodes. You may only query the Next() attribute in a list.
Definition at line 1133 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
BUF_SIZE
Definition at line 1224 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLAttribute() [1/2]
tinyxml2::XMLAttribute::XMLAttribute () [inline], [private]
Definition at line 1226 of file tinyxml2.h.
~XMLAttribute()
virtual tinyxml2::XMLAttribute::~XMLAttribute () [inline], [private], [virtual]
Definition at line 1227 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute().
XMLAttribute() [2/2]
tinyxml2::XMLAttribute::XMLAttribute (const XMLAttribute &) [private]
Member Function Documentation
BoolValue()
bool tinyxml2::XMLAttribute::BoolValue () const [inline]
Query as a boolean. See IntValue()
Definition at line 1174 of file tinyxml2.h.
DoubleValue()
double tinyxml2::XMLAttribute::DoubleValue () const [inline]
Query as a double. See IntValue()
Definition at line 1180 of file tinyxml2.h.
FloatValue()
float tinyxml2::XMLAttribute::FloatValue () const [inline]
Query as a float. See IntValue()
Definition at line 1186 of file tinyxml2.h.
GetLineNum()
int tinyxml2::XMLAttribute::GetLineNum () const [inline]
Gets the line number the attribute is in, if the document was parsed from a file.
Definition at line 1144 of file tinyxml2.h.
Int64Value()
int64_t tinyxml2::XMLAttribute::Int64Value () const [inline]
Definition at line 1161 of file tinyxml2.h.
IntValue()
int tinyxml2::XMLAttribute::IntValue () const [inline]
IntValue interprets the attribute as an integer, and returns the value. If the value isn't an integer, 0 will be returned. There is no error checking; use QueryIntValue() if you need error checking.
Definition at line 1155 of file tinyxml2.h.
Name()
const char * tinyxml2::XMLAttribute::Name () const
The name of the attribute.
Definition at line 1346 of file tinyxml2.cpp.
References _name, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLPrinter::VisitEnter().
Next()
const XMLAttribute* tinyxml2::XMLAttribute::Next () const [inline]
The next attribute in the list.
Definition at line 1147 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
operator=()
void tinyxml2::XMLAttribute::operator= (const XMLAttribute &) [private]
ParseDeep()
char * tinyxml2::XMLAttribute::ParseDeep (char * p, bool processEntities, int * curLineNumPtr) [private]
Definition at line 1356 of file tinyxml2.cpp.
References _name, _value, tinyxml2::StrPair::ATTRIBUTE_VALUE, tinyxml2::StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES, tinyxml2::StrPair::ParseName(), tinyxml2::StrPair::ParseText(), and tinyxml2::XMLUtil::SkipWhiteSpace().
Referenced by tinyxml2::XMLElement::ParseAttributes().
QueryBoolValue()
 XMLError tinyxml2::XMLAttribute::QueryBoolValue (bool * value) const
See QueryIntValue.
Definition at line 1417 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToBool(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryBoolAttribute().
QueryDoubleValue()
 XMLError tinyxml2::XMLAttribute::QueryDoubleValue (double * value) const
See QueryIntValue.
Definition at line 1435 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToDouble(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryDoubleAttribute().
QueryFloatValue()
 XMLError tinyxml2::XMLAttribute::QueryFloatValue (float * value) const
See QueryIntValue.
Definition at line 1426 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToFloat(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryFloatAttribute().
QueryInt64Value()
 XMLError tinyxml2::XMLAttribute::QueryInt64Value (int64_t * value) const
See QueryIntValue.
Definition at line 1408 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToInt64(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryInt64Attribute().
QueryIntValue()
 XMLError tinyxml2::XMLAttribute::QueryIntValue (int * value) const
QueryIntValue interprets the attribute as an integer, and returns the value in the provided parameter. The function will return XML_SUCCESS on success, and XML_WRONG_ATTRIBUTE_TYPE if the conversion is not successful.
Definition at line 1390 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToInt(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryIntAttribute().
QueryUnsignedValue()
 XMLError tinyxml2::XMLAttribute::QueryUnsignedValue (unsigned int * value) const
See QueryIntValue.
Definition at line 1399 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToUnsigned(), Value(), tinyxml2::XML_SUCCESS, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryUnsignedAttribute().
SetAttribute() [1/7]
void tinyxml2::XMLAttribute::SetAttribute (const char * value)
Set the attribute to a string value.
Definition at line 1444 of file tinyxml2.cpp.
References _value, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::SetAttribute().
SetAttribute() [2/7]
void tinyxml2::XMLAttribute::SetAttribute (int value)
Set the attribute to value.
Definition at line 1450 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [3/7]
void tinyxml2::XMLAttribute::SetAttribute (unsigned value)
Set the attribute to value.
Definition at line 1458 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [4/7]
void tinyxml2::XMLAttribute::SetAttribute (int64_t value)
Set the attribute to value.
Definition at line 1466 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [5/7]
void tinyxml2::XMLAttribute::SetAttribute (bool value)
Set the attribute to value.
Definition at line 1475 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [6/7]
void tinyxml2::XMLAttribute::SetAttribute (double value)
Set the attribute to value.
Definition at line 1482 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [7/7]
void tinyxml2::XMLAttribute::SetAttribute (float value)
Set the attribute to value.
Definition at line 1489 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetName()
void tinyxml2::XMLAttribute::SetName (const char * name) [private]
Definition at line 1384 of file tinyxml2.cpp.
References _name, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute().
UnsignedValue()
unsigned tinyxml2::XMLAttribute::UnsignedValue () const [inline]
Query as an unsigned integer. See IntValue()
Definition at line 1168 of file tinyxml2.h.
Value()
const char * tinyxml2::XMLAttribute::Value () const
The value of the attribute.
Definition at line 1351 of file tinyxml2.cpp.
References _value, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::Attribute(), QueryBoolValue(), QueryDoubleValue(), QueryFloatValue(), QueryInt64Value(), QueryIntValue(), tinyxml2::XMLElement::QueryStringAttribute(), QueryUnsignedValue(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
Friends And Related Function Documentation
XMLElement
friend class XMLElement [friend]
Definition at line 1135 of file tinyxml2.h.
Member Data Documentation
_memPool
 MemPool* tinyxml2::XMLAttribute::_memPool [private]
Definition at line 1239 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute().
_name
 StrPair tinyxml2::XMLAttribute::_name [mutable], [private]
Definition at line 1235 of file tinyxml2.h.
Referenced by Name(), ParseDeep(), and SetName().
_next
 XMLAttribute* tinyxml2::XMLAttribute::_next [private]
Definition at line 1238 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLElement::~XMLElement().
_parseLineNum
int tinyxml2::XMLAttribute::_parseLineNum [private]
Definition at line 1237 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::ParseAttributes().
_value
 StrPair tinyxml2::XMLAttribute::_value [mutable], [private]
Definition at line 1236 of file tinyxml2.h.
Referenced by ParseDeep(), SetAttribute(), and Value().
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp