tinyxml2::XMLElement Class Reference
#include <tinyxml2.h>
Public Types
enum ElementClosingType { OPEN,
 CLOSED,
 CLOSING
 }
Public Member Functions
const char * Name () const
Get the name of an element (which is the Value() of the node.)
void SetName (const char *str, bool staticMem=false)
Set the name of the element.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual bool Accept (XMLVisitor *visitor) const
const char * Attribute (const char *name, const char *value=0) const
int IntAttribute (const char *name, int defaultValue=0) const
unsigned UnsignedAttribute (const char *name, unsigned defaultValue=0) const
See IntAttribute()
int64_t Int64Attribute (const char *name, int64_t defaultValue=0) const
See IntAttribute()
bool BoolAttribute (const char *name, bool defaultValue=false) const
See IntAttribute()
double DoubleAttribute (const char *name, double defaultValue=0) const
See IntAttribute()
float FloatAttribute (const char *name, float defaultValue=0) const
See IntAttribute()
 XMLError QueryIntAttribute (const char *name, int *value) const
 XMLError QueryUnsignedAttribute (const char *name, unsigned int *value) const
See QueryIntAttribute()
 XMLError QueryInt64Attribute (const char *name, int64_t *value) const
See QueryIntAttribute()
 XMLError QueryBoolAttribute (const char *name, bool *value) const
See QueryIntAttribute()
 XMLError QueryDoubleAttribute (const char *name, double *value) const
See QueryIntAttribute()
 XMLError QueryFloatAttribute (const char *name, float *value) const
See QueryIntAttribute()
 XMLError QueryStringAttribute (const char *name, const char **value) const
See QueryIntAttribute()
 XMLError QueryAttribute (const char *name, int *value) const
 XMLError QueryAttribute (const char *name, unsigned int *value) const
 XMLError QueryAttribute (const char *name, int64_t *value) const
 XMLError QueryAttribute (const char *name, bool *value) const
 XMLError QueryAttribute (const char *name, double *value) const
 XMLError QueryAttribute (const char *name, float *value) const
void SetAttribute (const char *name, const char *value)
Sets the named attribute to value.
void SetAttribute (const char *name, int value)
Sets the named attribute to value.
void SetAttribute (const char *name, unsigned value)
Sets the named attribute to value.
void SetAttribute (const char *name, int64_t value)
Sets the named attribute to value.
void SetAttribute (const char *name, bool value)
Sets the named attribute to value.
void SetAttribute (const char *name, double value)
Sets the named attribute to value.
void SetAttribute (const char *name, float value)
Sets the named attribute to value.
void DeleteAttribute (const char *name)
const XMLAttribute * FirstAttribute () const
Return the first attribute in the list.
const XMLAttribute * FindAttribute (const char *name) const
Query a specific attribute in the list.
const char * GetText () const
void SetText (const char *inText)
void SetText (int value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (unsigned value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (int64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (bool value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (double value)
Convenience method for setting text inside an element. See SetText() for important limitations.
void SetText (float value)
Convenience method for setting text inside an element. See SetText() for important limitations.
 XMLError QueryIntText (int *ival) const
 XMLError QueryUnsignedText (unsigned *uval) const
See QueryIntText()
 XMLError QueryInt64Text (int64_t *uval) const
See QueryIntText()
 XMLError QueryBoolText (bool *bval) const
See QueryIntText()
 XMLError QueryDoubleText (double *dval) const
See QueryIntText()
 XMLError QueryFloatText (float *fval) const
See QueryIntText()
int IntText (int defaultValue=0) const
unsigned UnsignedText (unsigned defaultValue=0) const
See QueryIntText()
int64_t Int64Text (int64_t defaultValue=0) const
See QueryIntText()
bool BoolText (bool defaultValue=false) const
See QueryIntText()
double DoubleText (double defaultValue=0) const
See QueryIntText()
float FloatText (float defaultValue=0) const
See QueryIntText()
 ElementClosingType ClosingType () const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Protected Member Functions
char * ParseDeep (char *p, StrPair *parentEndTag, int *curLineNumPtr)
Private Types
enum { BUF_SIZE = 200
 }
Private Member Functions
 XMLElement (XMLDocument *doc)
virtual ~XMLElement ()
 XMLElement (const XMLElement &)
void operator= (const XMLElement &)
 XMLAttribute * FindOrCreateAttribute (const char *name)
char * ParseAttributes (char *p, int *curLineNumPtr)
 XMLAttribute * CreateAttribute ()
Static Private Member Functions
static void DeleteAttribute (XMLAttribute *attribute)
Private Attributes
 ElementClosingType _closingType
 XMLAttribute * _rootAttribute
Friends
class XMLDocument
Additional Inherited Members
Detailed Description
The element is a container class. It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Definition at line 1247 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
BUF_SIZE
Definition at line 1633 of file tinyxml2.h.
ElementClosingType
enum tinyxml2::XMLElement::ElementClosingType
Enumerator
OPEN
CLOSED
CLOSING
Definition at line 1608 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLElement() [1/2]
tinyxml2::XMLElement::XMLElement (XMLDocument * doc) [private]
Definition at line 1498 of file tinyxml2.cpp.
~XMLElement()
tinyxml2::XMLElement::~XMLElement () [private], [virtual]
Definition at line 1505 of file tinyxml2.cpp.
References tinyxml2::XMLAttribute::_next, _rootAttribute, and DeleteAttribute().
XMLElement() [2/2]
tinyxml2::XMLElement::XMLElement (const XMLElement &) [private]
Member Function Documentation
Accept()
bool tinyxml2::XMLElement::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
 http://www.saxproject.org/
 http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for `visiting`.
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode .
Definition at line 1966 of file tinyxml2.cpp.
References _rootAttribute, tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::NextSibling(), TIXMLASSERT, tinyxml2::XMLVisitor::VisitEnter(), and tinyxml2::XMLVisitor::VisitExit().
Attribute()
const char * tinyxml2::XMLElement::Attribute (const char * name, const char * value = 0) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. For example:
const char* value = ele->Attribute( "foo" );
The 'value' parameter is normally null. However, if specified, the attribute will only be returned if the 'name' and 'value' match. This allow you to write code:
if ( ele->Attribute( "foo", "bar" ) ) callFooIsBar();
rather than:
if ( ele->Attribute( "foo" ) ) {
    if ( strcmp( ele->Attribute( "foo" ), "bar" ) == 0 ) callFooIsBar();
}
Definition at line 1526 of file tinyxml2.cpp.
References FindAttribute(), tinyxml2::XMLUtil::StringEqual(), and tinyxml2::XMLAttribute::Value().
Referenced by ParseAttributes().
BoolAttribute()
bool tinyxml2::XMLElement::BoolAttribute (const char * name, bool defaultValue = false) const
See IntAttribute()
Definition at line 1559 of file tinyxml2.cpp.
References QueryBoolAttribute().
BoolText()
bool tinyxml2::XMLElement::BoolText (bool defaultValue = false) const
See QueryIntText()
Definition at line 1746 of file tinyxml2.cpp.
References QueryBoolText().
ClosingType()
 ElementClosingType tinyxml2::XMLElement::ClosingType () const [inline]
Definition at line 1613 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::ParseDeep().
CreateAttribute()
 XMLAttribute * tinyxml2::XMLElement::CreateAttribute () [private]
Definition at line 1884 of file tinyxml2.cpp.
References tinyxml2::XMLDocument::_attributePool, tinyxml2::XMLNode::_document, and TIXMLASSERT.
Referenced by FindOrCreateAttribute(), and ParseAttributes().
DeleteAttribute() [1/2]
void tinyxml2::XMLElement::DeleteAttribute (const char * name)
Delete an attribute.
Definition at line 1796 of file tinyxml2.cpp.
References tinyxml2::XMLAttribute::_next, _rootAttribute, and tinyxml2::XMLUtil::StringEqual().
Referenced by ParseAttributes(), and ~XMLElement().
DeleteAttribute() [2/2]
void tinyxml2::XMLElement::DeleteAttribute (XMLAttribute * attribute) [static], [private]
Definition at line 1874 of file tinyxml2.cpp.
References tinyxml2::XMLAttribute::_memPool, tinyxml2::MemPool::Free(), and tinyxml2::XMLAttribute::~XMLAttribute().
DoubleAttribute()
double tinyxml2::XMLElement::DoubleAttribute (const char * name, double defaultValue = 0) const
See IntAttribute()
Definition at line 1566 of file tinyxml2.cpp.
References QueryDoubleAttribute().
DoubleText()
double tinyxml2::XMLElement::DoubleText (double defaultValue = 0) const
See QueryIntText()
Definition at line 1753 of file tinyxml2.cpp.
References QueryDoubleText().
FindAttribute()
const XMLAttribute * tinyxml2::XMLElement::FindAttribute (const char * name) const
Query a specific attribute in the list.
Definition at line 1515 of file tinyxml2.cpp.
References tinyxml2::XMLAttribute::_next, _rootAttribute, and tinyxml2::XMLUtil::StringEqual().
Referenced by Attribute().
FindOrCreateAttribute()
 XMLAttribute * tinyxml2::XMLElement::FindOrCreateAttribute (const char * name) [private]
Definition at line 1768 of file tinyxml2.cpp.
References tinyxml2::XMLAttribute::_next, _rootAttribute, CreateAttribute(), tinyxml2::XMLAttribute::SetName(), tinyxml2::XMLUtil::StringEqual(), and TIXMLASSERT.
FirstAttribute()
const XMLAttribute* tinyxml2::XMLElement::FirstAttribute () const [inline]
Return the first attribute in the list.
Definition at line 1472 of file tinyxml2.h.
Referenced by ShallowClone(), and ShallowEqual().
FloatAttribute()
float tinyxml2::XMLElement::FloatAttribute (const char * name, float defaultValue = 0) const
See IntAttribute()
Definition at line 1573 of file tinyxml2.cpp.
References QueryFloatAttribute().
FloatText()
float tinyxml2::XMLElement::FloatText (float defaultValue = 0) const
See QueryIntText()
Definition at line 1760 of file tinyxml2.cpp.
References QueryFloatText().
GetText()
const char * tinyxml2::XMLElement::GetText () const
Convenience function for easy access to the text inside an element. Although easy and concise, GetText() is limited compared to getting the XMLText child and accessing it directly.
If the first child of 'this' is a XMLText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
<foo>This is text</foo>
    const char* str = fooElement->GetText();
'str' will be a pointer to `This is text`.
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
    <foo>This is <b>text</b></foo>
 GetText() will return `This is `.
Definition at line 1580 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::ToText(), and tinyxml2::XMLNode::Value().
Int64Attribute()
int64_t tinyxml2::XMLElement::Int64Attribute (const char * name, int64_t defaultValue = 0) const
See IntAttribute()
Definition at line 1552 of file tinyxml2.cpp.
References QueryInt64Attribute().
Int64Text()
int64_t tinyxml2::XMLElement::Int64Text (int64_t defaultValue = 0) const
See QueryIntText()
Definition at line 1739 of file tinyxml2.cpp.
References QueryInt64Text().
IntAttribute()
int tinyxml2::XMLElement::IntAttribute (const char * name, int defaultValue = 0) const
Given an attribute name, IntAttribute() returns the value of the attribute interpreted as an integer. The default value will be returned if the attribute isn't present, or if there is an error. (For a method with error checking, see QueryIntAttribute()).
Definition at line 1538 of file tinyxml2.cpp.
References QueryIntAttribute().
IntText()
int tinyxml2::XMLElement::IntText (int defaultValue = 0) const
Definition at line 1725 of file tinyxml2.cpp.
References QueryIntText().
Name()
const char* tinyxml2::XMLElement::Name () const [inline]
Get the name of an element (which is the Value() of the node.)
Definition at line 1252 of file tinyxml2.h.
Referenced by World::parseAntennas(), ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), ShallowEqual(), tinyxml2::XMLNode::ToElementWithName(), and tinyxml2::XMLPrinter::VisitEnter().
operator=()
void tinyxml2::XMLElement::operator= (const XMLElement &) [private]
ParseAttributes()
char * tinyxml2::XMLElement::ParseAttributes (char * p, int * curLineNumPtr) [private]
Definition at line 1815 of file tinyxml2.cpp.
References _closingType, tinyxml2::XMLNode::_document, tinyxml2::XMLAttribute::_next, tinyxml2::XMLDocument::_parseCurLineNum, tinyxml2::XMLNode::_parseLineNum, tinyxml2::XMLAttribute::_parseLineNum, _rootAttribute, Attribute(), CLOSED, CreateAttribute(), DeleteAttribute(), tinyxml2::XMLUtil::IsNameStartChar(), tinyxml2::XMLAttribute::Name(), Name(), tinyxml2::XMLAttribute::ParseDeep(), tinyxml2::XMLDocument::ProcessEntities(), tinyxml2::XMLDocument::SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), TIXMLASSERT, tinyxml2::XML_ERROR_PARSING_ATTRIBUTE, and tinyxml2::XML_ERROR_PARSING_ELEMENT.
Referenced by ParseDeep().
ParseDeep()
char * tinyxml2::XMLElement::ParseDeep (char * p, StrPair * parentEndTag, int * curLineNumPtr) [protected], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1898 of file tinyxml2.cpp.
References _closingType, tinyxml2::XMLNode::_value, CLOSING, tinyxml2::StrPair::Empty(), OPEN, ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::StrPair::ParseName(), and tinyxml2::XMLUtil::SkipWhiteSpace().
QueryAttribute() [1/6]
 XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, int * value) const [inline]
Given an attribute name, QueryAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. It is overloaded for the primitive types, and is a generally more convenient replacement of QueryIntAttribute() and related functions.
If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryAttribute( "foo", &value );        // if "foo" isn't found, value will still be 10
Definition at line 1404 of file tinyxml2.h.
QueryAttribute() [2/6]
 XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, unsigned int * value) const [inline]
Definition at line 1408 of file tinyxml2.h.
QueryAttribute() [3/6]
 XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, int64_t * value) const [inline]
Definition at line 1412 of file tinyxml2.h.
QueryAttribute() [4/6]
 XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, bool * value) const [inline]
Definition at line 1416 of file tinyxml2.h.
QueryAttribute() [5/6]
 XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, double * value) const [inline]
Definition at line 1420 of file tinyxml2.h.
QueryAttribute() [6/6]
 XMLError tinyxml2::XMLElement::QueryAttribute (const char * name, float * value) const [inline]
Definition at line 1424 of file tinyxml2.h.
QueryBoolAttribute()
 XMLError tinyxml2::XMLElement::QueryBoolAttribute (const char * name, bool * value) const [inline]
See QueryIntAttribute()
Definition at line 1351 of file tinyxml2.h.
References tinyxml2::XMLAttribute::QueryBoolValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by BoolAttribute().
QueryBoolText()
 XMLError tinyxml2::XMLElement::QueryBoolText (bool * bval) const
See QueryIntText()
Definition at line 1687 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToBool(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by BoolText().
QueryDoubleAttribute()
 XMLError tinyxml2::XMLElement::QueryDoubleAttribute (const char * name, double * value) const [inline]
See QueryIntAttribute()
Definition at line 1359 of file tinyxml2.h.
References tinyxml2::XMLAttribute::QueryDoubleValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by DoubleAttribute().
QueryDoubleText()
 XMLError tinyxml2::XMLElement::QueryDoubleText (double * dval) const
See QueryIntText()
Definition at line 1700 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToDouble(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by DoubleText().
QueryFloatAttribute()
 XMLError tinyxml2::XMLElement::QueryFloatAttribute (const char * name, float * value) const [inline]
See QueryIntAttribute()
Definition at line 1367 of file tinyxml2.h.
References tinyxml2::XMLAttribute::QueryFloatValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by FloatAttribute().
QueryFloatText()
 XMLError tinyxml2::XMLElement::QueryFloatText (float * fval) const
See QueryIntText()
Definition at line 1713 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToFloat(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by FloatText().
QueryInt64Attribute()
 XMLError tinyxml2::XMLElement::QueryInt64Attribute (const char * name, int64_t * value) const [inline]
See QueryIntAttribute()
Definition at line 1342 of file tinyxml2.h.
References tinyxml2::XMLAttribute::QueryInt64Value(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by Int64Attribute().
QueryInt64Text()
 XMLError tinyxml2::XMLElement::QueryInt64Text (int64_t * uval) const
See QueryIntText()
Definition at line 1674 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToInt64(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by Int64Text().
QueryIntAttribute()
 XMLError tinyxml2::XMLElement::QueryIntAttribute (const char * name, int * value) const [inline]
Given an attribute name, QueryIntAttribute() returns XML_SUCCESS, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryIntAttribute( "foo", &value );     // if "foo" isn't found, value will still be 10
Definition at line 1324 of file tinyxml2.h.
References tinyxml2::XMLAttribute::QueryIntValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by IntAttribute().
QueryIntText()
 XMLError tinyxml2::XMLElement::QueryIntText (int * ival) const
Convenience method to query the value of a child text node. This is probably best shown by example. Given you have a document is this form:
    <point>
        <x>1</x>
        <y>1.4</y>
    </point>
The QueryIntText() and similar functions provide a safe and easier way to get to the `value` of x and y.
    int x = 0;
    float y = 0;    // types of x and y are contrived for example
    const XMLElement* xElement = pointElement->FirstChildElement( "x" );
    const XMLElement* yElement = pointElement->FirstChildElement( "y" );
    xElement->QueryIntText( &x );
    yElement->QueryFloatText( &y );
Returns
XML_SUCCESS (0) on success, XML_CAN_NOT_CONVERT_TEXT if the text cannot be converted to the requested type, and XML_NO_TEXT_NODE if there is no child text to query.
Definition at line 1648 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLUtil::ToInt(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by IntText().
QueryStringAttribute()
 XMLError tinyxml2::XMLElement::QueryStringAttribute (const char * name, const char ** value) const [inline]
See QueryIntAttribute()
Definition at line 1376 of file tinyxml2.h.
References tinyxml2::XMLAttribute::Value(), tinyxml2::XML_NO_ATTRIBUTE, and tinyxml2::XML_SUCCESS.
QueryUnsignedAttribute()
 XMLError tinyxml2::XMLElement::QueryUnsignedAttribute (const char * name, unsigned int * value) const [inline]
See QueryIntAttribute()
Definition at line 1333 of file tinyxml2.h.
References tinyxml2::XMLAttribute::QueryUnsignedValue(), and tinyxml2::XML_NO_ATTRIBUTE.
Referenced by UnsignedAttribute().
QueryUnsignedText()
 XMLError tinyxml2::XMLElement::QueryUnsignedText (unsigned * uval) const
See QueryIntText()
Definition at line 1661 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLUtil::ToUnsigned(), tinyxml2::XMLNode::Value(), tinyxml2::XML_CAN_NOT_CONVERT_TEXT, tinyxml2::XML_NO_TEXT_NODE, and tinyxml2::XML_SUCCESS.
Referenced by UnsignedText().
SetAttribute() [1/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, const char * value) [inline]
Sets the named attribute to value.
Definition at line 1429 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
Referenced by ShallowClone().
SetAttribute() [2/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, int value) [inline]
Sets the named attribute to value.
Definition at line 1434 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [3/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, unsigned value) [inline]
Sets the named attribute to value.
Definition at line 1439 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [4/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, int64_t value) [inline]
Sets the named attribute to value.
Definition at line 1445 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [5/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, bool value) [inline]
Sets the named attribute to value.
Definition at line 1451 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [6/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, double value) [inline]
Sets the named attribute to value.
Definition at line 1456 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
SetAttribute() [7/7]
void tinyxml2::XMLElement::SetAttribute (const char * name, float value) [inline]
Sets the named attribute to value.
Definition at line 1461 of file tinyxml2.h.
References tinyxml2::XMLAttribute::SetAttribute().
SetName()
void tinyxml2::XMLElement::SetName (const char * str, bool staticMem = false) [inline]
Set the name of the element.
Definition at line 1256 of file tinyxml2.h.
Referenced by tinyxml2::XMLDocument::NewElement().
SetText() [1/7]
void tinyxml2::XMLElement::SetText (const char * inText)
Convenience function for easy access to the text inside an element. Although easy and concise, SetText() is limited compared to creating an XMLText child and mutating it directly.
If the first child of 'this' is a XMLText, SetText() sets its value to the given string, otherwise it will create a first child that is an XMLText.
This is a convenient method for setting the text of simple contained text:
<foo>This is text</foo>
    fooElement->SetText( "Hullaballoo!" );
<foo>Hullaballoo!</foo>
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then it will not change `This is text`, but rather prefix it with a text element:
    <foo>Hullaballoo!<b>This is text</b></foo>
For this XML:
    <foo />
 SetText() will generate
    <foo>Hullaballoo!</foo>
Definition at line 1589 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::GetDocument(), tinyxml2::XMLNode::InsertFirstChild(), tinyxml2::XMLDocument::NewText(), tinyxml2::XMLNode::SetValue(), and tinyxml2::XMLNode::ToText().
Referenced by SetText().
SetText() [2/7]
void tinyxml2::XMLElement::SetText (int value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1600 of file tinyxml2.cpp.
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
SetText() [3/7]
void tinyxml2::XMLElement::SetText (unsigned value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1608 of file tinyxml2.cpp.
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
SetText() [4/7]
void tinyxml2::XMLElement::SetText (int64_t value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1616 of file tinyxml2.cpp.
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
SetText() [5/7]
void tinyxml2::XMLElement::SetText (bool value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1624 of file tinyxml2.cpp.
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
SetText() [6/7]
void tinyxml2::XMLElement::SetText (double value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1640 of file tinyxml2.cpp.
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
SetText() [7/7]
void tinyxml2::XMLElement::SetText (float value)
Convenience method for setting text inside an element. See SetText() for important limitations.
Definition at line 1632 of file tinyxml2.cpp.
References BUF_SIZE, SetText(), and tinyxml2::XMLUtil::ToStr().
ShallowClone()
 XMLNode * tinyxml2::XMLElement::ShallowClone (XMLDocument * document) const [virtual]
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode .
Definition at line 1927 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, FirstAttribute(), tinyxml2::XMLDocument::NewElement(), tinyxml2::XMLAttribute::Next(), SetAttribute(), and tinyxml2::XMLNode::Value().
ShallowEqual()
bool tinyxml2::XMLElement::ShallowEqual (const XMLNode * compare) const [virtual]
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode .
Definition at line 1940 of file tinyxml2.cpp.
References FirstAttribute(), Name(), tinyxml2::XMLAttribute::Next(), tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, tinyxml2::XMLNode::ToElement(), and tinyxml2::XMLAttribute::Value().
ToElement() [1/2]
virtual XMLElement* tinyxml2::XMLElement::ToElement () [inline], [virtual]
Safely cast to an Element, or null.
Reimplemented from tinyxml2::XMLNode .
Definition at line 1260 of file tinyxml2.h.
ToElement() [2/2]
virtual const XMLElement* tinyxml2::XMLElement::ToElement () const [inline], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1263 of file tinyxml2.h.
UnsignedAttribute()
unsigned tinyxml2::XMLElement::UnsignedAttribute (const char * name, unsigned defaultValue = 0) const
See IntAttribute()
Definition at line 1545 of file tinyxml2.cpp.
References QueryUnsignedAttribute().
UnsignedText()
unsigned tinyxml2::XMLElement::UnsignedText (unsigned defaultValue = 0) const
See QueryIntText()
Definition at line 1732 of file tinyxml2.cpp.
References QueryUnsignedText().
Friends And Related Function Documentation
XMLDocument
friend class XMLDocument [friend]
Definition at line 1249 of file tinyxml2.h.
Member Data Documentation
_closingType
 ElementClosingType tinyxml2::XMLElement::_closingType [private]
Definition at line 1634 of file tinyxml2.h.
Referenced by ParseAttributes(), and ParseDeep().
_rootAttribute
 XMLAttribute* tinyxml2::XMLElement::_rootAttribute [private]
Definition at line 1638 of file tinyxml2.h.
Referenced by Accept(), DeleteAttribute(), FindAttribute(), FindOrCreateAttribute(), ParseAttributes(), and ~XMLElement().
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp