tinyxml2::XMLPrinter Class Reference
#include <tinyxml2.h>
Public Member Functions
 XMLPrinter (FILE *file=0, bool compact=false, int depth=0)
virtual ~XMLPrinter ()
void PushHeader (bool writeBOM, bool writeDeclaration)
void OpenElement (const char *name, bool compactMode=false)
void PushAttribute (const char *name, const char *value)
If streaming, add an attribute to an open element.
void PushAttribute (const char *name, int value)
void PushAttribute (const char *name, unsigned value)
void PushAttribute (const char *name, int64_t value)
void PushAttribute (const char *name, bool value)
void PushAttribute (const char *name, double value)
virtual void CloseElement (bool compactMode=false)
If streaming, close the Element.
void PushText (const char *text, bool cdata=false)
Add a text node.
void PushText (int value)
Add a text node from an integer.
void PushText (unsigned value)
Add a text node from an unsigned.
void PushText (int64_t value)
Add a text node from an unsigned.
void PushText (bool value)
Add a text node from a bool.
void PushText (float value)
Add a text node from a float.
void PushText (double value)
Add a text node from a double.
void PushComment (const char *comment)
Add a comment.
void PushDeclaration (const char *value)
void PushUnknown (const char *value)
virtual bool VisitEnter (const XMLDocument &)
Visit a document.
virtual bool VisitExit (const XMLDocument &)
Visit a document.
virtual bool VisitEnter (const XMLElement &element, const XMLAttribute *attribute)
Visit an element.
virtual bool VisitExit (const XMLElement &element)
Visit an element.
virtual bool Visit (const XMLText &text)
Visit a text node.
virtual bool Visit (const XMLComment &comment)
Visit a comment node.
virtual bool Visit (const XMLDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const XMLUnknown &unknown)
Visit an unknown node.
const char * CStr () const
int CStrSize () const
void ClearBuffer ()
Protected Member Functions
virtual bool CompactMode (const XMLElement &)
virtual void PrintSpace (int depth)
void Print (const char *format,...)
void Write (const char *data, size_t size)
void Write (const char *data)
void Putc (char ch)
void SealElementIfJustOpened ()
Protected Attributes
bool _elementJustOpened
 DynArray< const char *, 10 > _stack
Private Types
enum { ENTITY_RANGE = 64,
 BUF_SIZE = 200
 }
Private Member Functions
void PrintString (const char *, bool restrictedEntitySet)
 XMLPrinter (const XMLPrinter &)
 XMLPrinter & operator= (const XMLPrinter &)
Private Attributes
bool _firstElement
FILE * _fp
int _depth
int _textDepth
bool _processEntities
bool _compactMode
bool _entityFlag [ ENTITY_RANGE]
bool _restrictedEntityFlag [ ENTITY_RANGE]
 DynArray< char, 20 > _buffer
Detailed Description
Printing functionality. The XMLPrinter gives you more options than the XMLDocument::Print() method.
It can:
Print to memory.
Print to a file you provide.
Print XML without a XMLDocument.
Print to Memory
XMLPrinter printer;
doc.Print( &printer );
SomeFunction( printer.CStr() );
Print to a File
You provide the file pointer.
XMLPrinter printer( fp );
doc.Print( &printer );
Print without a XMLDocument
When loading, an XML parser is very useful. However, sometimes when saving, it just gets in the way. The code is often set up for streaming, and constructing the DOM is just overhead.
The Printer supports the streaming case. The following code prints out a trivially simple XML file without ever creating an XML document.
XMLPrinter printer( fp );
printer.OpenElement( "foo" );
printer.PushAttribute( "foo", "bar" );
printer.CloseElement();
Definition at line 2175 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
ENTITY_RANGE
BUF_SIZE
Definition at line 2288 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLPrinter() [1/2]
tinyxml2::XMLPrinter::XMLPrinter (FILE * file = 0, bool compact = false, int depth = 0)
Construct the printer. If the FILE* is specified, this will print to the FILE. Else it will print to memory, and the result is available in CStr(). If 'compact' is set to true, then output is created with only required whitespace and newlines.
Definition at line 2410 of file tinyxml2.cpp.
References _buffer, _entityFlag, _restrictedEntityFlag, ENTITY_RANGE, tinyxml2::DynArray< T, INITIAL_SIZE >::Push(), TIXMLASSERT, and tinyxml2::Entity::value.
~XMLPrinter()
virtual tinyxml2::XMLPrinter::~XMLPrinter () [inline], [virtual]
Definition at line 2185 of file tinyxml2.h.
XMLPrinter() [2/2]
tinyxml2::XMLPrinter::XMLPrinter (const XMLPrinter &) [private]
Member Function Documentation
ClearBuffer()
void tinyxml2::XMLPrinter::ClearBuffer () [inline]
If in print to memory mode, reset the buffer to the beginning.
Definition at line 2256 of file tinyxml2.h.
CloseElement()
void tinyxml2::XMLPrinter::CloseElement (bool compactMode = false) [virtual]
If streaming, close the Element.
Definition at line 2633 of file tinyxml2.cpp.
References _depth, _elementJustOpened, _stack, _textDepth, tinyxml2::DynArray< T, INITIAL_SIZE >::Pop(), PrintSpace(), Putc(), and Write().
Referenced by VisitExit().
CompactMode()
virtual bool tinyxml2::XMLPrinter::CompactMode (const XMLElement &) [inline], [protected], [virtual]
Definition at line 2263 of file tinyxml2.h.
Referenced by VisitEnter(), and VisitExit().
CStr()
const char* tinyxml2::XMLPrinter::CStr () const [inline]
If in print to memory mode, return a pointer to the XML file in memory.
Definition at line 2241 of file tinyxml2.h.
CStrSize()
int tinyxml2::XMLPrinter::CStrSize () const [inline]
If in print to memory mode, return the size of the XML file in memory. (Note the size returned includes the terminating null.)
Definition at line 2249 of file tinyxml2.h.
OpenElement()
void tinyxml2::XMLPrinter::OpenElement (const char * name, bool compactMode = false)
If streaming, start writing an element. The element must be closed with CloseElement()
Definition at line 2561 of file tinyxml2.cpp.
References _depth, _elementJustOpened, _firstElement, _stack, _textDepth, PrintSpace(), tinyxml2::DynArray< T, INITIAL_SIZE >::Push(), Putc(), SealElementIfJustOpened(), and Write().
Referenced by VisitEnter().
operator=()
 XMLPrinter& tinyxml2::XMLPrinter::operator= (const XMLPrinter &) [private]
Print()
void tinyxml2::XMLPrinter::Print (const char * format, ...) [protected]
Definition at line 2438 of file tinyxml2.cpp.
References _fp.
PrintSpace()
void tinyxml2::XMLPrinter::PrintSpace (int depth) [protected], [virtual]
Prints out the space before an element. You may override to change the space and tabs used. A PrintSpace() override should call Print().
Definition at line 2486 of file tinyxml2.cpp.
References Write().
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
PrintString()
void tinyxml2::XMLPrinter::PrintString (const char * p, bool restrictedEntitySet) [private]
Definition at line 2494 of file tinyxml2.cpp.
References _entityFlag, _processEntities, _restrictedEntityFlag, ENTITY_RANGE, Putc(), TIXMLASSERT, and Write().
Referenced by PushAttribute(), and PushText().
PushAttribute() [1/6]
void tinyxml2::XMLPrinter::PushAttribute (const char * name, const char * value)
If streaming, add an attribute to an open element.
Definition at line 2582 of file tinyxml2.cpp.
References _elementJustOpened, PrintString(), Putc(), TIXMLASSERT, and Write().
Referenced by PushAttribute(), and VisitEnter().
PushAttribute() [2/6]
void tinyxml2::XMLPrinter::PushAttribute (const char * name, int value)
Definition at line 2593 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
PushAttribute() [3/6]
void tinyxml2::XMLPrinter::PushAttribute (const char * name, unsigned value)
Definition at line 2601 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
PushAttribute() [4/6]
void tinyxml2::XMLPrinter::PushAttribute (const char * name, int64_t value)
Definition at line 2609 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
PushAttribute() [5/6]
void tinyxml2::XMLPrinter::PushAttribute (const char * name, bool value)
Definition at line 2617 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
PushAttribute() [6/6]
void tinyxml2::XMLPrinter::PushAttribute (const char * name, double value)
Definition at line 2625 of file tinyxml2.cpp.
References BUF_SIZE, PushAttribute(), and tinyxml2::XMLUtil::ToStr().
PushComment()
void tinyxml2::XMLPrinter::PushComment (const char * comment)
Add a comment.
Definition at line 2733 of file tinyxml2.cpp.
References _compactMode, _depth, _firstElement, _textDepth, PrintSpace(), Putc(), SealElementIfJustOpened(), and Write().
Referenced by Visit().
PushDeclaration()
void tinyxml2::XMLPrinter::PushDeclaration (const char * value)
Definition at line 2748 of file tinyxml2.cpp.
References _compactMode, _depth, _firstElement, _textDepth, PrintSpace(), Putc(), SealElementIfJustOpened(), and Write().
Referenced by Visit().
PushHeader()
void tinyxml2::XMLPrinter::PushHeader (bool writeBOM, bool writeDeclaration)
If streaming, write the BOM and declaration.
Definition at line 2549 of file tinyxml2.cpp.
Referenced by VisitEnter().
PushText() [1/7]
void tinyxml2::XMLPrinter::PushText (const char * text, bool cdata = false)
Add a text node.
Definition at line 2671 of file tinyxml2.cpp.
References _depth, _textDepth, PrintString(), SealElementIfJustOpened(), and Write().
Referenced by PushText(), and Visit().
PushText() [2/7]
void tinyxml2::XMLPrinter::PushText (int value)
Add a text node from an integer.
Definition at line 2693 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
PushText() [3/7]
void tinyxml2::XMLPrinter::PushText (unsigned value)
Add a text node from an unsigned.
Definition at line 2701 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
PushText() [4/7]
void tinyxml2::XMLPrinter::PushText (int64_t value)
Add a text node from an unsigned.
Definition at line 2686 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
PushText() [5/7]
void tinyxml2::XMLPrinter::PushText (bool value)
Add a text node from a bool.
Definition at line 2709 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
PushText() [6/7]
void tinyxml2::XMLPrinter::PushText (float value)
Add a text node from a float.
Definition at line 2717 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
PushText() [7/7]
void tinyxml2::XMLPrinter::PushText (double value)
Add a text node from a double.
Definition at line 2725 of file tinyxml2.cpp.
References BUF_SIZE, PushText(), and tinyxml2::XMLUtil::ToStr().
PushUnknown()
void tinyxml2::XMLPrinter::PushUnknown (const char * value)
Definition at line 2763 of file tinyxml2.cpp.
References _compactMode, _depth, _firstElement, _textDepth, PrintSpace(), Putc(), SealElementIfJustOpened(), and Write().
Referenced by Visit().
Putc()
void tinyxml2::XMLPrinter::Putc (char ch) [protected]
Definition at line 2473 of file tinyxml2.cpp.
References _buffer, _fp, and tinyxml2::DynArray< T, INITIAL_SIZE >::PushArr().
Referenced by CloseElement(), OpenElement(), PrintString(), PushAttribute(), PushComment(), PushDeclaration(), PushUnknown(), and SealElementIfJustOpened().
SealElementIfJustOpened()
void tinyxml2::XMLPrinter::SealElementIfJustOpened () [protected]
Definition at line 2661 of file tinyxml2.cpp.
References _elementJustOpened, and Putc().
Referenced by OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
Visit() [1/4]
bool tinyxml2::XMLPrinter::Visit (const XMLText &) [virtual]
Visit a text node.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2811 of file tinyxml2.cpp.
References tinyxml2::XMLText::CData(), PushText(), and tinyxml2::XMLNode::Value().
Visit() [2/4]
bool tinyxml2::XMLPrinter::Visit (const XMLComment &) [virtual]
Visit a comment node.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2818 of file tinyxml2.cpp.
References PushComment(), and tinyxml2::XMLNode::Value().
Visit() [3/4]
bool tinyxml2::XMLPrinter::Visit (const XMLDeclaration &) [virtual]
Visit a declaration.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2824 of file tinyxml2.cpp.
References PushDeclaration(), and tinyxml2::XMLNode::Value().
Visit() [4/4]
bool tinyxml2::XMLPrinter::Visit (const XMLUnknown &) [virtual]
Visit an unknown node.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2831 of file tinyxml2.cpp.
References PushUnknown(), and tinyxml2::XMLNode::Value().
VisitEnter() [1/2]
bool tinyxml2::XMLPrinter::VisitEnter (const XMLDocument &) [virtual]
Visit a document.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2778 of file tinyxml2.cpp.
References _processEntities, tinyxml2::XMLDocument::HasBOM(), tinyxml2::XMLDocument::ProcessEntities(), and PushHeader().
VisitEnter() [2/2]
bool tinyxml2::XMLPrinter::VisitEnter (const XMLElement & , const XMLAttribute *) [virtual]
Visit an element.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2788 of file tinyxml2.cpp.
References _compactMode, CompactMode(), tinyxml2::XMLAttribute::Name(), tinyxml2::XMLElement::Name(), tinyxml2::XMLAttribute::Next(), OpenElement(), tinyxml2::XMLNode::Parent(), PushAttribute(), tinyxml2::XMLNode::ToElement(), and tinyxml2::XMLAttribute::Value().
VisitExit() [1/2]
virtual bool tinyxml2::XMLPrinter::VisitExit (const XMLDocument &) [inline], [virtual]
Visit a document.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2225 of file tinyxml2.h.
VisitExit() [2/2]
bool tinyxml2::XMLPrinter::VisitExit (const XMLElement &) [virtual]
Visit an element.
Reimplemented from tinyxml2::XMLVisitor .
Definition at line 2804 of file tinyxml2.cpp.
References CloseElement(), and CompactMode().
Write() [1/2]
void tinyxml2::XMLPrinter::Write (const char * data, size_t size) [protected]
Definition at line 2460 of file tinyxml2.cpp.
References _buffer, _fp, and tinyxml2::DynArray< T, INITIAL_SIZE >::PushArr().
Referenced by CloseElement(), OpenElement(), PrintSpace(), PrintString(), PushAttribute(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
Write() [2/2]
void tinyxml2::XMLPrinter::Write (const char * data) [inline], [protected]
Definition at line 2271 of file tinyxml2.h.
References Write().
Referenced by Write().
Member Data Documentation
_buffer
 DynArray< char, 20 > tinyxml2::XMLPrinter::_buffer [private]
Definition at line 2295 of file tinyxml2.h.
Referenced by Putc(), Write(), and XMLPrinter().
_compactMode
bool tinyxml2::XMLPrinter::_compactMode [private]
Definition at line 2286 of file tinyxml2.h.
Referenced by PushComment(), PushDeclaration(), PushUnknown(), and VisitEnter().
_depth
int tinyxml2::XMLPrinter::_depth [private]
Definition at line 2283 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
_elementJustOpened
bool tinyxml2::XMLPrinter::_elementJustOpened [protected]
Definition at line 2275 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushAttribute(), and SealElementIfJustOpened().
_entityFlag
bool tinyxml2::XMLPrinter::_entityFlag[ ENTITY_RANGE] [private]
Definition at line 2292 of file tinyxml2.h.
Referenced by PrintString(), and XMLPrinter().
_firstElement
bool tinyxml2::XMLPrinter::_firstElement [private]
Definition at line 2281 of file tinyxml2.h.
Referenced by OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
_fp
FILE* tinyxml2::XMLPrinter::_fp [private]
Definition at line 2282 of file tinyxml2.h.
Referenced by Print(), Putc(), and Write().
_processEntities
bool tinyxml2::XMLPrinter::_processEntities [private]
Definition at line 2285 of file tinyxml2.h.
Referenced by PrintString(), and VisitEnter().
_restrictedEntityFlag
bool tinyxml2::XMLPrinter::_restrictedEntityFlag[ ENTITY_RANGE] [private]
Definition at line 2293 of file tinyxml2.h.
Referenced by PrintString(), and XMLPrinter().
_stack
 DynArray< const char*, 10 > tinyxml2::XMLPrinter::_stack [protected]
Definition at line 2276 of file tinyxml2.h.
Referenced by CloseElement(), and OpenElement().
_textDepth
int tinyxml2::XMLPrinter::_textDepth [private]
Definition at line 2284 of file tinyxml2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp