Tablet Class Reference
#include <Tablet.h>
Public Member Functions
 Tablet (Map *m, long id, Point *initPosition, Clock *clock)
virtual ~Tablet ()
string getName () override
string toString () override
Point * move (MovementType type) override
bool tryConnect (HoldableAgent::CONNECTION_TYPE type) override
Additional Inherited Members
Detailed Description
Definition at line 18 of file Tablet.h.
Constructor & Destructor Documentation
Tablet()
Tablet::Tablet (Map * m, long id, Point * initPosition, Clock * clock) [explicit]
Definition at line 13 of file Tablet.cpp.
~Tablet()
Tablet::~Tablet () [virtual]
Definition at line 19 of file Tablet.cpp.
Member Function Documentation
getName()
string Tablet::getName () [inline], [override], [virtual]
This function is used to get the name of the class. It is a pure virtual function, all subclasses implment it and return the actual name of the class.
Returns
the name of the class.
Reimplemented from HoldableAgent .
Definition at line 23 of file Tablet.h.
References toString().
move()
Point* Tablet::move (MovementType type) [inline], [override], [virtual]
Implements MovableAgent .
Definition at line 28 of file Tablet.h.
References LocatableAgent::getLocation(), and tryConnect().
toString()
string Tablet::toString () [override], [virtual]
Builds a string with of the relevant information of the class. It is useful to output on the console or in a file the description of concrete agents.
Returns
a string representation of the class content. The values of the members are written in this string.
Reimplemented from HoldableAgent .
Definition at line 23 of file Tablet.cpp.
References HoldableAgent::toString().
Referenced by getName().
tryConnect()
bool Tablet::tryConnect (HoldableAgent::CONNECTION_TYPE type) [override], [virtual]
Implements HoldableAgent .
Definition at line 27 of file Tablet.cpp.
Referenced by move().
The documentation for this class was generated from the following files:
include/ Tablet.h
src/ Tablet.cpp