tinyxml2::XMLText Class Reference
#include <tinyxml2.h>
Public Member Functions
virtual bool Accept (XMLVisitor *visitor) const
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
void SetCData (bool isCData)
Declare whether this should be CDATA or standard text.
bool CData () const
Returns true if this is a CDATA text element.
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Protected Member Functions
 XMLText (XMLDocument *doc)
virtual ~XMLText ()
char * ParseDeep (char *p, StrPair *parentEndTag, int *curLineNumPtr)
Private Member Functions
 XMLText (const XMLText &)
 XMLText & operator= (const XMLText &)
Private Attributes
bool _isCData
Friends
class XMLDocument
Additional Inherited Members
Detailed Description
XML text.
Note that a text node can have child element nodes, for example:
<root>This is <b>bold</b></root>
A text node can have 2 ways to output the next. `normal` output and CDATA. It will default to the mode it was parsed from the XML file and you generally want to leave it alone, but you can change the output mode with SetCData() and query it with CData().
Definition at line 984 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLText() [1/2]
tinyxml2::XMLText::XMLText (XMLDocument * doc) [inline], [explicit], [protected]
Definition at line 1010 of file tinyxml2.h.
~XMLText()
virtual tinyxml2::XMLText::~XMLText () [inline], [protected], [virtual]
Definition at line 1011 of file tinyxml2.h.
XMLText() [2/2]
tinyxml2::XMLText::XMLText (const XMLText &) [private]
Member Function Documentation
Accept()
bool tinyxml2::XMLText::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
 http://www.saxproject.org/
 http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for `visiting`.
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode .
Definition at line 1193 of file tinyxml2.cpp.
References TIXMLASSERT, and tinyxml2::XMLVisitor::Visit().
CData()
bool tinyxml2::XMLText::CData () const [inline]
Returns true if this is a CDATA text element.
Definition at line 1002 of file tinyxml2.h.
Referenced by ParseDeep(), ShallowClone(), and tinyxml2::XMLPrinter::Visit().
operator=()
 XMLText& tinyxml2::XMLText::operator= (const XMLText &) [private]
ParseDeep()
char * tinyxml2::XMLText::ParseDeep (char * p, StrPair * parentEndTag, int * curLineNumPtr) [protected], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1147 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_parseLineNum, tinyxml2::XMLNode::_value, CData(), tinyxml2::COLLAPSE_WHITESPACE, tinyxml2::StrPair::NEEDS_NEWLINE_NORMALIZATION, tinyxml2::StrPair::NEEDS_WHITESPACE_COLLAPSING, tinyxml2::StrPair::ParseText(), tinyxml2::XMLDocument::ProcessEntities(), tinyxml2::XMLDocument::SetError(), tinyxml2::StrPair::TEXT_ELEMENT, tinyxml2::StrPair::TEXT_ELEMENT_LEAVE_ENTITIES, tinyxml2::XMLDocument::WhitespaceMode(), tinyxml2::XML_ERROR_PARSING_CDATA, and tinyxml2::XML_ERROR_PARSING_TEXT.
SetCData()
void tinyxml2::XMLText::SetCData (bool isCData) [inline]
Declare whether this should be CDATA or standard text.
Definition at line 998 of file tinyxml2.h.
Referenced by tinyxml2::XMLDocument::Identify(), and ShallowClone().
ShallowClone()
 XMLNode * tinyxml2::XMLText::ShallowClone (XMLDocument * document) const [virtual]
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode .
Definition at line 1174 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, CData(), tinyxml2::XMLDocument::NewText(), SetCData(), and tinyxml2::XMLNode::Value().
ShallowEqual()
bool tinyxml2::XMLText::ShallowEqual (const XMLNode * compare) const [virtual]
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode .
Definition at line 1185 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, tinyxml2::XMLNode::ToText(), and tinyxml2::XMLNode::Value().
ToText() [1/2]
virtual XMLText* tinyxml2::XMLText::ToText () [inline], [virtual]
Safely cast to Text, or null.
Reimplemented from tinyxml2::XMLNode .
Definition at line 990 of file tinyxml2.h.
ToText() [2/2]
virtual const XMLText* tinyxml2::XMLText::ToText () const [inline], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 993 of file tinyxml2.h.
Friends And Related Function Documentation
XMLDocument
friend class XMLDocument [friend]
Definition at line 986 of file tinyxml2.h.
Member Data Documentation
_isCData
bool tinyxml2::XMLText::_isCData [private]
Definition at line 1016 of file tinyxml2.h.
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp