tinyxml2::XMLUnknown Class Reference
#include <tinyxml2.h>
Public Member Functions
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLUnknown * ToUnknown () const
virtual bool Accept (XMLVisitor *visitor) const
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Protected Member Functions
 XMLUnknown (XMLDocument *doc)
virtual ~XMLUnknown ()
char * ParseDeep (char *p, StrPair *parentEndTag, int *curLineNumPtr)
Private Member Functions
 XMLUnknown (const XMLUnknown &)
 XMLUnknown & operator= (const XMLUnknown &)
Friends
class XMLDocument
Additional Inherited Members
Detailed Description
Any tag that TinyXML-2 doesn't recognize is saved as an unknown. It is a tag of text, but should not be modified. It will be written back to the XML, unchanged, when the file is saved.
DTD tags get thrown into XMLUnknowns.
Definition at line 1098 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLUnknown() [1/2]
tinyxml2::XMLUnknown::XMLUnknown (XMLDocument * doc) [explicit], [protected]
Definition at line 1299 of file tinyxml2.cpp.
~XMLUnknown()
tinyxml2::XMLUnknown::~XMLUnknown () [protected], [virtual]
Definition at line 1304 of file tinyxml2.cpp.
XMLUnknown() [2/2]
tinyxml2::XMLUnknown::XMLUnknown (const XMLUnknown &) [private]
Member Function Documentation
Accept()
bool tinyxml2::XMLUnknown::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for `visiting`.
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode .
Definition at line 1338 of file tinyxml2.cpp.
References TIXMLASSERT, and tinyxml2::XMLVisitor::Visit().
operator=()
 XMLUnknown& tinyxml2::XMLUnknown::operator= (const XMLUnknown &) [private]
ParseDeep()
char * tinyxml2::XMLUnknown::ParseDeep (char * p, StrPair * parentEndTag, int * curLineNumPtr) [protected], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1309 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_parseLineNum, tinyxml2::XMLNode::_value, tinyxml2::StrPair::NEEDS_NEWLINE_NORMALIZATION, tinyxml2::StrPair::ParseText(), tinyxml2::XMLDocument::SetError(), and tinyxml2::XML_ERROR_PARSING_UNKNOWN.
ShallowClone()
 XMLNode * tinyxml2::XMLUnknown::ShallowClone (XMLDocument * document) const [virtual]
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode .
Definition at line 1320 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLDocument::NewUnknown(), and tinyxml2::XMLNode::Value().
ShallowEqual()
bool tinyxml2::XMLUnknown::ShallowEqual (const XMLNode * compare) const [virtual]
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode .
Definition at line 1330 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::StringEqual(), TIXMLASSERT, tinyxml2::XMLNode::ToUnknown(), and tinyxml2::XMLNode::Value().
ToUnknown() [1/2]
virtual XMLUnknown* tinyxml2::XMLUnknown::ToUnknown () [inline], [virtual]
Safely cast to an Unknown, or null.
Reimplemented from tinyxml2::XMLNode .
Definition at line 1102 of file tinyxml2.h.
ToUnknown() [2/2]
virtual const XMLUnknown* tinyxml2::XMLUnknown::ToUnknown () const [inline], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1105 of file tinyxml2.h.
Friends And Related Function Documentation
XMLDocument
friend class XMLDocument [friend]
Definition at line 1100 of file tinyxml2.h.
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp