RandomNumberGenerator Class Reference
#include <RandomNumberGenerator.h>
Public Member Functions
uniform_int_distribution< int > getUnifIntDistribution () const
uniform_real_distribution< double > getUnifDoubleDistribution () const
normal_distribution< double > getNormalDoubleDistribution () const
std::mt19937 & getGenerator ()
double * generateNormal2Double (double m1, double sd1, double m2, double sd2, int n)
double generateNormalDouble (double m, double sd)
double * generateNormalDouble (double m, double sd, int n)
double * generateTruncatedNormalDouble (const double a, const double b, const double m, const double sd, const unsigned long n)
double generateUniformDouble (double min, double max)
double * generateUniformDouble (double min, double max, int n)
int generateUniformInt (int min, int max)
int * generateUniformInt (int min, int max, int n)
int generateBinomialInt (int max, double p)
int * generateBinomialInt (int max, double p, int n)
Static Public Member Functions
static RandomNumberGenerator * instance ()
Private Member Functions
 RandomNumberGenerator ()
 RandomNumberGenerator (const RandomNumberGenerator &)
 RandomNumberGenerator & operator= (const RandomNumberGenerator &)
Private Attributes
uniform_int_distribution< int > m_unif_int_distribution
uniform_real_distribution< double > m_unif_double_distribution
normal_distribution< double > m_normal_double_distribution
binomial_distribution< int > m_binomial_distribution
std::mt19937 m_generator
Static Private Attributes
static RandomNumberGenerator * m_instance = nullptr
Detailed Description
Definition at line 18 of file RandomNumberGenerator.h.
Constructor & Destructor Documentation
RandomNumberGenerator() [1/2]
RandomNumberGenerator::RandomNumberGenerator () [private]
Definition at line 20 of file RandomNumberGenerator.cpp.
RandomNumberGenerator() [2/2]
RandomNumberGenerator::RandomNumberGenerator (const RandomNumberGenerator &) [private]
Member Function Documentation
generateBinomialInt() [1/2]
int RandomNumberGenerator::generateBinomialInt (int max, double p)
Definition at line 80 of file RandomNumberGenerator.cpp.
Referenced by World::generatePopulation().
generateBinomialInt() [2/2]
int * RandomNumberGenerator::generateBinomialInt (int max, double p, int n)
Definition at line 88 of file RandomNumberGenerator.cpp.
generateNormal2Double()
double * RandomNumberGenerator::generateNormal2Double (double m1, double sd1, double m2, double sd2, int n)
Definition at line 25 of file RandomNumberGenerator.cpp.
Referenced by World::generatePopulation().
generateNormalDouble() [1/2]
double RandomNumberGenerator::generateNormalDouble (double m, double sd)
Definition at line 122 of file RandomNumberGenerator.cpp.
Referenced by World::generatePopulation().
generateNormalDouble() [2/2]
double * RandomNumberGenerator::generateNormalDouble (double m, double sd, int n)
Definition at line 98 of file RandomNumberGenerator.cpp.
generateTruncatedNormalDouble()
double * RandomNumberGenerator::generateTruncatedNormalDouble (const double a, const double b, const double m, const double sd, const unsigned long n)
Definition at line 108 of file RandomNumberGenerator.cpp.
Referenced by World::generatePopulation().
generateUniformDouble() [1/2]
double RandomNumberGenerator::generateUniformDouble (double min, double max)
Definition at line 43 of file RandomNumberGenerator.cpp.
Referenced by utils::generatePoints(), World::generatePopulation(), and Person::randomWalk().
generateUniformDouble() [2/2]
double * RandomNumberGenerator::generateUniformDouble (double min, double max, int n)
Definition at line 52 of file RandomNumberGenerator.cpp.
generateUniformInt() [1/2]
int RandomNumberGenerator::generateUniformInt (int min, int max)
Definition at line 62 of file RandomNumberGenerator.cpp.
Referenced by World::generatePopulation().
generateUniformInt() [2/2]
int * RandomNumberGenerator::generateUniformInt (int min, int max, int n)
Definition at line 70 of file RandomNumberGenerator.cpp.
getGenerator()
std::mt19937& RandomNumberGenerator::getGenerator () [inline]
Definition at line 39 of file RandomNumberGenerator.h.
getNormalDoubleDistribution()
normal_distribution<double> RandomNumberGenerator::getNormalDoubleDistribution () const [inline]
Definition at line 35 of file RandomNumberGenerator.h.
getUnifDoubleDistribution()
uniform_real_distribution<double> RandomNumberGenerator::getUnifDoubleDistribution () const [inline]
Definition at line 31 of file RandomNumberGenerator.h.
getUnifIntDistribution()
uniform_int_distribution<int> RandomNumberGenerator::getUnifIntDistribution () const [inline]
Definition at line 27 of file RandomNumberGenerator.h.
instance()
static RandomNumberGenerator* RandomNumberGenerator::instance () [inline], [static]
Definition at line 20 of file RandomNumberGenerator.h.
Referenced by utils::generatePoints(), World::generatePopulation(), and Person::randomWalk().
operator=()
 RandomNumberGenerator& RandomNumberGenerator::operator= (const RandomNumberGenerator &) [private]
Member Data Documentation
m_binomial_distribution
binomial_distribution<int> RandomNumberGenerator::m_binomial_distribution [private]
Definition at line 81 of file RandomNumberGenerator.h.
m_generator
std::mt19937 RandomNumberGenerator::m_generator [private]
Definition at line 83 of file RandomNumberGenerator.h.
m_instance
 RandomNumberGenerator * RandomNumberGenerator::m_instance = nullptr [static], [private]
Definition at line 77 of file RandomNumberGenerator.h.
m_normal_double_distribution
normal_distribution<double> RandomNumberGenerator::m_normal_double_distribution [private]
Definition at line 80 of file RandomNumberGenerator.h.
m_unif_double_distribution
uniform_real_distribution<double> RandomNumberGenerator::m_unif_double_distribution [private]
Definition at line 79 of file RandomNumberGenerator.h.
m_unif_int_distribution
uniform_int_distribution<int> RandomNumberGenerator::m_unif_int_distribution [private]
Definition at line 78 of file RandomNumberGenerator.h.
The documentation for this class was generated from the following files:
include/ RandomNumberGenerator.h
src/ RandomNumberGenerator.cpp