IDGenerator Class Reference
#include <IDGenerator.h>
Public Member Functions
unsigned long next ()
Static Public Member Functions
static IDGenerator * instance ()
Private Member Functions
 IDGenerator ()
Private Attributes
unsigned long m_id
Static Private Attributes
static IDGenerator * m_instance = nullptr
Detailed Description
Definition at line 13 of file IDGenerator.h.
Constructor & Destructor Documentation
IDGenerator()
IDGenerator::IDGenerator () [inline], [private]
Definition at line 27 of file IDGenerator.h.
Referenced by instance().
Member Function Documentation
instance()
static IDGenerator* IDGenerator::instance () [inline], [static]
Definition at line 15 of file IDGenerator.h.
References IDGenerator(), and m_instance.
Referenced by World::generateAntennas(), World::generateMobilePhones(), World::generatePopulation(), and World::parseAntennas().
next()
unsigned long IDGenerator::next () [inline]
Definition at line 22 of file IDGenerator.h.
References m_id.
Referenced by World::generateAntennas(), World::generateMobilePhones(), World::generatePopulation(), and World::parseAntennas().
Member Data Documentation
m_id
unsigned long IDGenerator::m_id [private]
Definition at line 31 of file IDGenerator.h.
Referenced by next().
m_instance
 IDGenerator * IDGenerator::m_instance = nullptr [static], [private]
Definition at line 30 of file IDGenerator.h.
Referenced by instance().
The documentation for this class was generated from the following files:
include/ IDGenerator.h
src/ IDGenerator.cpp