LocatableAgent Class Reference
#include <LocatableAgent.h>
Public Member Functions
 LocatableAgent (Map *m, long id, Point *initLocation, Clock *clock)
virtual ~LocatableAgent ()
string getName () override
string toString () override
virtual Point * getLocation () const
virtual void setLocation (Point *location)
string dumpLocation ()
Private Attributes
Point * m_location
Detailed Description
Definition at line 21 of file LocatableAgent.h.
Constructor & Destructor Documentation
LocatableAgent()
LocatableAgent::LocatableAgent (Map * m, long id, Point * initLocation, Clock * clock) [explicit]
Definition at line 20 of file LocatableAgent.cpp.
References m_location.
~LocatableAgent()
LocatableAgent::~LocatableAgent () [virtual]
Definition at line 26 of file LocatableAgent.cpp.
Member Function Documentation
dumpLocation()
string LocatableAgent::dumpLocation ()
Definition at line 49 of file LocatableAgent.cpp.
References Agent::getClock(), Clock::getCurrentTime(), Agent::getId(), and getLocation().
Referenced by World::runSimulation().
getLocation()
Point * LocatableAgent::getLocation () const [virtual]
Definition at line 31 of file LocatableAgent.cpp.
References m_location.
Referenced by Antenna::computePower(), Antenna::computeSignalQuality(), dumpLocation(), Tablet::move(), Person::move(), Antenna::registerEvent(), HoldableAgent::setHolder(), toString(), and MobilePhone::tryConnectNaiveAlgorithm().
getName()
string LocatableAgent::getName () [inline], [override], [virtual]
This function is used to get the name of the class. It is a pure virtual function, all subclasses implment it and return the actual name of the class.
Returns
the name of the class.
Implements Agent .
Reimplemented in Person , MovableAgent , MobilePhone , and Tablet .
Definition at line 27 of file LocatableAgent.h.
setLocation()
void LocatableAgent::setLocation (Point * location) [virtual]
Reimplemented in Person , and HoldableAgent .
Definition at line 35 of file LocatableAgent.cpp.
References m_location.
Referenced by HoldableAgent::setLocation(), and Person::setLocation().
toString()
string LocatableAgent::toString () [override], [virtual]
Builds a string with of the relevant information of the class. It is useful to output on the console or in a file the description of concrete agents.
Returns
a string representation of the class content. The values of the members are written in this string.
Implements Agent .
Reimplemented in Person , MovableAgent , MobilePhone , and Tablet .
Definition at line 39 of file LocatableAgent.cpp.
References Agent::getId(), getLocation(), and m_location.
Referenced by ImmovableAgent::toString(), and MovableAgent::toString().
Member Data Documentation
m_location
Point* LocatableAgent::m_location [private]
Definition at line 41 of file LocatableAgent.h.
Referenced by getLocation(), LocatableAgent(), setLocation(), and toString().
The documentation for this class was generated from the following files:
include/ LocatableAgent.h
src/ LocatableAgent.cpp