Row Class Reference
#include <CSVparser.hpp>
Public Member Functions
 Row (const vector< std::string > &)
 ~Row (void)
unsigned int size (void) const
void push (const string &)
bool set (const string &, const string &)
template<typename T >
const T getValue (unsigned int pos) const
const string operator[] (unsigned int) const
const string operator[] (const string &valueName) const
Private Attributes
const vector< string > _header
vector< string > _values
Friends
ostream & operator<< (ostream &os, const Row &row)
ofstream & operator<< (ofstream &os, const Row &row)
Detailed Description
Definition at line 20 of file CSVparser.hpp.
Constructor & Destructor Documentation
Row()
Row::Row (const vector< std::string > &)
Definition at line 173 of file CSVParser.cpp.
~Row()
Row::~Row (void)
Definition at line 177 of file CSVParser.cpp.
Member Function Documentation
getValue()
template<typename T >
const T Row::getValue (unsigned int pos) const [inline]
Definition at line 37 of file CSVparser.hpp.
References operator<<().
operator[]() [1/2]
const string Row::operator[] (unsigned int valuePosition) const
Definition at line 202 of file CSVParser.cpp.
References _values.
operator[]() [2/2]
const string Row::operator[] (const string & valueName) const
Definition at line 208 of file CSVParser.cpp.
References _header, and _values.
push()
void Row::push (const string &)
Definition at line 184 of file CSVParser.cpp.
References _values.
Referenced by Parser::addRow(), and Parser::parseContent().
set()
bool Row::set (const string & key, const string & value)
Definition at line 188 of file CSVParser.cpp.
References _header, and _values.
size()
unsigned int Row::size (void) const
Definition at line 180 of file CSVParser.cpp.
References _values.
Referenced by Parser::parseContent().
Friends And Related Function Documentation
operator<< [1/2]
ostream& operator<< (ostream & os, const Row & row) [friend]
Definition at line 221 of file CSVParser.cpp.
operator<< [2/2]
ofstream& operator<< (ofstream & os, const Row & row) [friend]
Definition at line 228 of file CSVParser.cpp.
Member Data Documentation
_header
const vector<string> Row::_header [private]
Definition at line 31 of file CSVparser.hpp.
Referenced by operator[](), and set().
_values
vector<string> Row::_values [private]
Definition at line 32 of file CSVparser.hpp.
Referenced by operator<<(), operator[](), push(), set(), and size().
The documentation for this class was generated from the following files:
include/ CSVparser.hpp
src/ CSVParser.cpp