Person Class Reference
#include <Person.h>
Public Types
enum Gender { MALE,
 FEMALE
 }
enum AgeDistributions { NORMAL,
 UNIFORM
 }
Public Member Functions
 Person (Map *m, long id, Point *initPosition, Clock *clock, double initSpeed, int age, Gender gender)
virtual ~Person ()
string getName () override
string toString () override
string dumpDevices ()
bool hasDevices ()
int getAge () const
void setAge (int age)
Point * move (MovementType mvType) override
virtual void setLocation (Point *pt) override
void addDevice (string type, Agent *agent)
 Gender getGender () const
Private Member Functions
void randomWalk ()
Private Attributes
int m_age
 Gender m_gender
unordered_multimap< string, Agent * > m_idDevices
Detailed Description
Definition at line 26 of file Person.h.
Member Enumeration Documentation
AgeDistributions
enum Person::AgeDistributions
Enumerator
NORMAL
UNIFORM
Definition at line 31 of file Person.h.
Gender
enum Person::Gender
Enumerator
MALE
FEMALE
Definition at line 28 of file Person.h.
Constructor & Destructor Documentation
Person()
Person::Person (Map * m, long id, Point * initPosition, Clock * clock, double initSpeed, int age, Gender gender) [explicit]
Definition at line 33 of file Person.cpp.
~Person()
Person::~Person () [virtual]
Definition at line 38 of file Person.cpp.
Member Function Documentation
addDevice()
void Person::addDevice (string type, Agent * agent) [inline]
Definition at line 55 of file Person.h.
Referenced by World::generatePopulation().
dumpDevices()
string Person::dumpDevices ()
Definition at line 133 of file Person.cpp.
References Agent::getId(), m_idDevices, and Constants::sep.
Referenced by World::runSimulation().
getAge()
int Person::getAge () const
Definition at line 42 of file Person.cpp.
References m_age.
getGender()
 Person::Gender Person::getGender () const
Definition at line 144 of file Person.cpp.
References m_gender.
getName()
string Person::getName () [inline], [override], [virtual]
This function is used to get the name of the class. It is a pure virtual function, all subclasses implment it and return the actual name of the class.
Returns
the name of the class.
Reimplemented from MovableAgent .
Definition at line 39 of file Person.h.
hasDevices()
bool Person::hasDevices ()
Definition at line 115 of file Person.cpp.
References m_idDevices.
Referenced by setLocation().
move()
Point * Person::move (MovementType mvType) [override], [virtual]
Implements MovableAgent .
Definition at line 63 of file Person.cpp.
References LocatableAgent::getLocation(), RANDOM_WALK, and randomWalk().
Referenced by World::runSimulation().
randomWalk()
void Person::randomWalk () [private]
Definition at line 83 of file Person.cpp.
References RandomNumberGenerator::generateUniformDouble(), Map::getBoundary(), Map::getGlobalFactory(), LocatableAgent::getLocation(), Agent::getMap(), MovableAgent::getSpeed(), RandomNumberGenerator::instance(), utils::PI, setLocation(), and Rtnorm::x.
Referenced by move().
setAge()
void Person::setAge (int age)
Definition at line 46 of file Person.cpp.
References m_age.
setLocation()
void Person::setLocation (Point * pt) [override], [virtual]
Reimplemented from LocatableAgent .
Definition at line 119 of file Person.cpp.
References hasDevices(), m_idDevices, LocatableAgent::setLocation(), and HoldableAgent::setLocation().
Referenced by randomWalk().
toString()
string Person::toString () [override], [virtual]
Builds a string with of the relevant information of the class. It is useful to output on the console or in a file the description of concrete agents.
Returns
a string representation of the class content. The values of the members are written in this string.
Reimplemented from MovableAgent .
Definition at line 50 of file Person.cpp.
References Agent::getId(), m_age, m_gender, m_idDevices, and MovableAgent::toString().
Member Data Documentation
m_age
int Person::m_age [private]
Definition at line 62 of file Person.h.
Referenced by getAge(), setAge(), and toString().
m_gender
 Gender Person::m_gender [private]
Definition at line 63 of file Person.h.
Referenced by getGender(), and toString().
m_idDevices
unordered_multimap<string, Agent*> Person::m_idDevices [private]
Definition at line 64 of file Person.h.
Referenced by dumpDevices(), hasDevices(), setLocation(), and toString().
The documentation for this class was generated from the following files:
include/ Person.h
src/ Person.cpp