tinyxml2::StrPair Class Reference
#include <tinyxml2.h>
Public Types
enum {
 NEEDS_ENTITY_PROCESSING = 0x01,
 NEEDS_NEWLINE_NORMALIZATION = 0x02,
 NEEDS_WHITESPACE_COLLAPSING = 0x04,
 TEXT_ELEMENT = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
 TEXT_ELEMENT_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION,
 ATTRIBUTE_NAME = 0,
 ATTRIBUTE_VALUE = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
 ATTRIBUTE_VALUE_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION,
 COMMENT = NEEDS_NEWLINE_NORMALIZATION
 }
Public Member Functions
 StrPair ()
 ~StrPair ()
void Set (char *start, char *end, int flags)
const char * GetStr ()
bool Empty () const
void SetInternedStr (const char *str)
void SetStr (const char *str, int flags=0)
char * ParseText (char *in, const char *endTag, int strFlags, int *curLineNumPtr)
char * ParseName (char *in)
void TransferTo (StrPair *other)
void Reset ()
Private Types
enum { NEEDS_FLUSH = 0x100,
 NEEDS_DELETE = 0x200
 }
Private Member Functions
void CollapseWhitespace ()
 StrPair (const StrPair &other)
void operator= (const StrPair &other)
Private Attributes
int _flags
char * _start
char * _end
Detailed Description
Definition at line 135 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NEEDS_ENTITY_PROCESSING
NEEDS_NEWLINE_NORMALIZATION
NEEDS_WHITESPACE_COLLAPSING
TEXT_ELEMENT
TEXT_ELEMENT_LEAVE_ENTITIES
ATTRIBUTE_NAME
ATTRIBUTE_VALUE
ATTRIBUTE_VALUE_LEAVE_ENTITIES
COMMENT
Definition at line 138 of file tinyxml2.h.
anonymous enum
anonymous enum [private]
Enumerator
NEEDS_FLUSH
NEEDS_DELETE
Definition at line 185 of file tinyxml2.h.
Constructor & Destructor Documentation
StrPair() [1/2]
tinyxml2::StrPair::StrPair () [inline]
Definition at line 151 of file tinyxml2.h.
~StrPair()
tinyxml2::StrPair::~StrPair ()
Definition at line 138 of file tinyxml2.cpp.
References Reset().
StrPair() [2/2]
tinyxml2::StrPair::StrPair (const StrPair & other) [private]
Member Function Documentation
CollapseWhitespace()
void tinyxml2::StrPair::CollapseWhitespace () [private]
Definition at line 238 of file tinyxml2.cpp.
References _flags, _start, tinyxml2::XMLUtil::IsWhiteSpace(), NEEDS_DELETE, tinyxml2::XMLUtil::SkipWhiteSpace(), and TIXMLASSERT.
Referenced by GetStr().
Empty()
bool tinyxml2::StrPair::Empty () const [inline]
Definition at line 165 of file tinyxml2.h.
Referenced by tinyxml2::XMLDocument::ErrorStr(), tinyxml2::XMLNode::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
GetStr()
const char * tinyxml2::StrPair::GetStr ()
Definition at line 267 of file tinyxml2.cpp.
References _end, _flags, _start, CollapseWhitespace(), CR, tinyxml2::entities, tinyxml2::XMLUtil::GetCharacterRef(), tinyxml2::Entity::length, LF, NEEDS_DELETE, NEEDS_ENTITY_PROCESSING, NEEDS_FLUSH, NEEDS_NEWLINE_NORMALIZATION, NEEDS_WHITESPACE_COLLAPSING, tinyxml2::NUM_ENTITIES, tinyxml2::Entity::pattern, TIXMLASSERT, and tinyxml2::Entity::value.
Referenced by tinyxml2::XMLDocument::ErrorStr(), tinyxml2::XMLAttribute::Name(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLNode::Value(), and tinyxml2::XMLAttribute::Value().
operator=()
void tinyxml2::StrPair::operator= (const StrPair & other) [private]
ParseName()
char * tinyxml2::StrPair::ParseName (char * in)
Definition at line 218 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::IsNameChar(), tinyxml2::XMLUtil::IsNameStartChar(), and Set().
Referenced by tinyxml2::XMLAttribute::ParseDeep(), and tinyxml2::XMLElement::ParseDeep().
ParseText()
char * tinyxml2::StrPair::ParseText (char * in, const char * endTag, int strFlags, int * curLineNumPtr)
Definition at line 193 of file tinyxml2.cpp.
References Set(), and TIXMLASSERT.
Referenced by tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), and tinyxml2::XMLAttribute::ParseDeep().
Reset()
void tinyxml2::StrPair::Reset ()
Definition at line 169 of file tinyxml2.cpp.
References _end, _flags, _start, and NEEDS_DELETE.
Referenced by tinyxml2::XMLDocument::SetError(), SetStr(), TransferTo(), and ~StrPair().
Set()
void tinyxml2::StrPair::Set (char * start, char * end, int flags) [inline]
Definition at line 154 of file tinyxml2.h.
References TIXMLASSERT.
Referenced by ParseName(), and ParseText().
SetInternedStr()
void tinyxml2::StrPair::SetInternedStr (const char * str) [inline]
Definition at line 169 of file tinyxml2.h.
Referenced by tinyxml2::XMLNode::SetValue().
SetStr()
void tinyxml2::StrPair::SetStr (const char * str, int flags = 0)
Definition at line 180 of file tinyxml2.cpp.
References _end, _flags, _start, NEEDS_DELETE, Reset(), and TIXMLASSERT.
Referenced by tinyxml2::XMLAttribute::SetAttribute(), tinyxml2::XMLDocument::SetError(), tinyxml2::XMLAttribute::SetName(), and tinyxml2::XMLNode::SetValue().
TransferTo()
void tinyxml2::StrPair::TransferTo (StrPair * other)
Definition at line 144 of file tinyxml2.cpp.
References _end, _flags, _start, Reset(), and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::ParseDeep().
Member Data Documentation
_end
char* tinyxml2::StrPair::_end [private]
Definition at line 192 of file tinyxml2.h.
Referenced by GetStr(), Reset(), SetStr(), and TransferTo().
_flags
int tinyxml2::StrPair::_flags [private]
Definition at line 190 of file tinyxml2.h.
Referenced by CollapseWhitespace(), GetStr(), Reset(), SetStr(), and TransferTo().
_start
char* tinyxml2::StrPair::_start [private]
Definition at line 191 of file tinyxml2.h.
Referenced by CollapseWhitespace(), GetStr(), Reset(), SetStr(), and TransferTo().
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp