tinyxml2::XMLDocument Class Reference
#include <tinyxml2.h>
Classes
class DepthTracker
Public Member Functions
 XMLDocument (bool processEntities=true, Whitespace whitespaceMode= PRESERVE_WHITESPACE)
constructor
 ~XMLDocument ()
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
 XMLError Parse (const char *xml, size_t nBytes=(size_t)(-1))
 XMLError LoadFile (const char *filename)
 XMLError LoadFile (FILE *)
 XMLError SaveFile (const char *filename, bool compact=false)
 XMLError SaveFile (FILE *fp, bool compact=false)
bool ProcessEntities () const
 Whitespace WhitespaceMode () const
bool HasBOM () const
void SetBOM (bool useBOM)
 XMLElement * RootElement ()
const XMLElement * RootElement () const
void Print (XMLPrinter *streamer=0) const
virtual bool Accept (XMLVisitor *visitor) const
 XMLElement * NewElement (const char *name)
 XMLComment * NewComment (const char *comment)
 XMLText * NewText (const char *text)
 XMLDeclaration * NewDeclaration (const char *text=0)
 XMLUnknown * NewUnknown (const char *text)
void DeleteNode (XMLNode *node)
void ClearError ()
bool Error () const
Return true if there was an error parsing the document.
 XMLError ErrorID () const
Return the errorID.
const char * ErrorName () const
const char * ErrorStr () const
void PrintError () const
A (trivial) utility function that prints the ErrorStr() to stdout.
int ErrorLineNum () const
Return the line where the error occurred, or zero if unknown.
void Clear ()
Clear the document, resetting it to the initial state.
void DeepCopy (XMLDocument *target) const
char * Identify (char *p, XMLNode **node)
void MarkInUse (XMLNode *)
virtual XMLNode * ShallowClone (XMLDocument *) const
virtual bool ShallowEqual (const XMLNode *) const
Static Public Member Functions
static const char * ErrorIDToName (XMLError errorID)
Private Member Functions
 XMLDocument (const XMLDocument &)
void operator= (const XMLDocument &)
void Parse ()
void SetError (XMLError error, int lineNum, const char *format,...)
void PushDepth ()
void PopDepth ()
template<class NodeType , int PoolElementSize>
NodeType * CreateUnlinkedNode (MemPoolT< PoolElementSize > &pool)
Private Attributes
bool _writeBOM
bool _processEntities
 XMLError _errorID
 Whitespace _whitespaceMode
 StrPair _errorStr
int _errorLineNum
char * _charBuffer
int _parseCurLineNum
int _parsingDepth
 DynArray< XMLNode *, 10 > _unlinked
 MemPoolT< sizeof(XMLElement) > _elementPool
 MemPoolT< sizeof(XMLAttribute) > _attributePool
 MemPoolT< sizeof(XMLText) > _textPool
 MemPoolT< sizeof(XMLComment) > _commentPool
Static Private Attributes
static const char * _errorNames [ XML_ERROR_COUNT]
Friends
class XMLElement
class XMLNode
class XMLText
class XMLComment
class XMLDeclaration
class XMLUnknown
Additional Inherited Members
Detailed Description
A Document binds together all the functionality. It can be saved, loaded, and printed to the screen. All Nodes are connected and allocated to a Document. If the Document is deleted, all its Nodes are also deleted.
Definition at line 1653 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLDocument() [1/2]
tinyxml2::XMLDocument::XMLDocument (bool processEntities = true, Whitespace whitespaceMode = PRESERVE_WHITESPACE)
constructor
Definition at line 2006 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document.
~XMLDocument()
tinyxml2::XMLDocument::~XMLDocument ()
Definition at line 2028 of file tinyxml2.cpp.
References Clear().
XMLDocument() [2/2]
tinyxml2::XMLDocument::XMLDocument (const XMLDocument &) [private]
Member Function Documentation
Accept()
bool tinyxml2::XMLDocument::Accept (XMLVisitor * visitor) const [virtual]
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
 http://www.saxproject.org/
 http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for `visiting`.
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();
Implements tinyxml2::XMLNode .
Definition at line 726 of file tinyxml2.cpp.
References tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::NextSibling(), TIXMLASSERT, tinyxml2::XMLVisitor::VisitEnter(), and tinyxml2::XMLVisitor::VisitExit().
Referenced by Print().
Clear()
void tinyxml2::XMLDocument::Clear ()
Clear the document, resetting it to the initial state.
Definition at line 2047 of file tinyxml2.cpp.
References _attributePool, _charBuffer, _commentPool, _elementPool, _parsingDepth, _textPool, _unlinked, ClearError(), tinyxml2::XMLNode::DeleteChildren(), DeleteNode(), Error(), and TIXMLASSERT.
Referenced by DeepCopy(), LoadFile(), Parse(), and ~XMLDocument().
ClearError()
void tinyxml2::XMLDocument::ClearError () [inline]
Definition at line 1814 of file tinyxml2.h.
References tinyxml2::XML_SUCCESS.
Referenced by Clear(), and SaveFile().
CreateUnlinkedNode()
template<class NodeType , int PoolElementSize>
NodeType * tinyxml2::XMLDocument::CreateUnlinkedNode (MemPoolT< PoolElementSize > & pool) [inline], [private]
Definition at line 1923 of file tinyxml2.h.
References _unlinked, tinyxml2::MemPoolT< ITEM_SIZE >::Alloc(), tinyxml2::MemPoolT< ITEM_SIZE >::ItemSize(), and TIXMLASSERT.
DeepCopy()
void tinyxml2::XMLDocument::DeepCopy (XMLDocument * target) const
Copies this document to a target document. The target will be completely cleared before the copy. If you want to copy a sub-tree, see XMLNode::DeepClone().
NOTE: that the 'target' must be non-null.
Definition at line 2081 of file tinyxml2.cpp.
References Clear(), tinyxml2::XMLNode::FirstChild(), tinyxml2::XMLNode::InsertEndChild(), tinyxml2::XMLNode::NextSibling(), and TIXMLASSERT.
DeleteNode()
void tinyxml2::XMLDocument::DeleteNode (XMLNode * node)
Delete a node associated with this document. It will be unlinked from the DOM.
Definition at line 2149 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_document, tinyxml2::XMLNode::_memPool, tinyxml2::XMLNode::_parent, tinyxml2::XMLNode::DeleteChild(), tinyxml2::XMLNode::DeleteNode(), tinyxml2::MemPool::SetTracked(), and TIXMLASSERT.
Referenced by Clear().
Error()
bool tinyxml2::XMLDocument::Error () const [inline]
Return true if there was an error parsing the document.
Definition at line 1819 of file tinyxml2.h.
References tinyxml2::XML_SUCCESS.
Referenced by Clear(), Parse(), and tinyxml2::XMLNode::ParseDeep().
ErrorID()
 XMLError tinyxml2::XMLDocument::ErrorID () const [inline]
Return the errorID.
Definition at line 1823 of file tinyxml2.h.
ErrorIDToName()
const char * tinyxml2::XMLDocument::ErrorIDToName (XMLError errorID) [static]
Definition at line 2356 of file tinyxml2.cpp.
References _errorNames, TIXMLASSERT, and tinyxml2::XML_ERROR_COUNT.
Referenced by ErrorName(), and SetError().
ErrorLineNum()
int tinyxml2::XMLDocument::ErrorLineNum () const [inline]
Return the line where the error occurred, or zero if unknown.
Definition at line 1838 of file tinyxml2.h.
ErrorName()
const char * tinyxml2::XMLDocument::ErrorName () const
Definition at line 2375 of file tinyxml2.cpp.
References _errorID, and ErrorIDToName().
ErrorStr()
const char * tinyxml2::XMLDocument::ErrorStr () const
Returns a `long form` error description. A hopefully helpful diagnostic with location, line number, and/or additional info.
Definition at line 2364 of file tinyxml2.cpp.
References _errorStr, tinyxml2::StrPair::Empty(), and tinyxml2::StrPair::GetStr().
Referenced by PrintError().
HasBOM()
bool tinyxml2::XMLDocument::HasBOM () const [inline]
Returns true if this document has a leading Byte Order Mark of UTF8.
Definition at line 1735 of file tinyxml2.h.
Referenced by tinyxml2::XMLPrinter::VisitEnter().
Identify()
char * tinyxml2::XMLDocument::Identify (char * p, XMLNode ** node)
Definition at line 656 of file tinyxml2.cpp.
References _commentPool, _elementPool, _parseCurLineNum, tinyxml2::XMLNode::_parseLineNum, _textPool, tinyxml2::XMLText::SetCData(), tinyxml2::XMLUtil::SkipWhiteSpace(), tinyxml2::XMLUtil::StringEqual(), and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::ParseDeep().
LoadFile() [1/2]
 XMLError tinyxml2::XMLDocument::LoadFile (const char * filename)
Load an XML file from disk. Returns XML_SUCCESS (0) on success, or an errorID.
Definition at line 2167 of file tinyxml2.cpp.
References _errorID, tinyxml2::callfopen(), Clear(), SetError(), TIXMLASSERT, tinyxml2::XML_ERROR_FILE_COULD_NOT_BE_OPENED, and tinyxml2::XML_ERROR_FILE_NOT_FOUND.
Referenced by World::parseAntennas(), World::parsePersons(), and World::parseSimulationFile().
LoadFile() [2/2]
 XMLError tinyxml2::XMLDocument::LoadFile (FILE * fp)
Load an XML file from disk. You are responsible for providing and closing the FILE*.
NOTE: The file should be opened as binary (`rb`) not text in order for TinyXML-2 to correctly do newline normalization.
Returns XML_SUCCESS (0) on success, or an errorID.
Definition at line 2209 of file tinyxml2.cpp.
References _charBuffer, _errorID, Clear(), Parse(), SetError(), TIXMLASSERT, tinyxml2::XML_ERROR_EMPTY_DOCUMENT, and tinyxml2::XML_ERROR_FILE_READ_ERROR.
MarkInUse()
void tinyxml2::XMLDocument::MarkInUse (XMLNode * node)
Definition at line 2034 of file tinyxml2.cpp.
References tinyxml2::XMLNode::_parent, _unlinked, and TIXMLASSERT.
Referenced by tinyxml2::XMLNode::DeleteNode(), and tinyxml2::XMLNode::InsertChildPreamble().
NewComment()
 XMLComment * tinyxml2::XMLDocument::NewComment (const char * comment)
Create a new Comment associated with this Document. The memory for the Comment is managed by the Document.
Definition at line 2102 of file tinyxml2.cpp.
References _commentPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLComment::ShallowClone().
NewDeclaration()
 XMLDeclaration * tinyxml2::XMLDocument::NewDeclaration (const char * text = 0)
Create a new Declaration associated with this Document. The memory for the object is managed by the Document.
If the 'text' param is null, the standard declaration is used.:
    <?xml version="1.0" encoding="UTF-8"?>
Definition at line 2118 of file tinyxml2.cpp.
References _commentPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLDeclaration::ShallowClone().
NewElement()
 XMLElement * tinyxml2::XMLDocument::NewElement (const char * name)
Create a new Element associated with this Document. The memory for the Element is managed by the Document.
Definition at line 2094 of file tinyxml2.cpp.
References _elementPool, and tinyxml2::XMLElement::SetName().
Referenced by tinyxml2::XMLElement::ShallowClone().
NewText()
 XMLText * tinyxml2::XMLDocument::NewText (const char * text)
Create a new Text associated with this Document. The memory for the Text is managed by the Document.
Definition at line 2110 of file tinyxml2.cpp.
References _textPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLElement::SetText(), and tinyxml2::XMLText::ShallowClone().
NewUnknown()
 XMLUnknown * tinyxml2::XMLDocument::NewUnknown (const char * text)
Create a new Unknown associated with this Document. The memory for the object is managed by the Document.
Definition at line 2126 of file tinyxml2.cpp.
References _commentPool, and tinyxml2::XMLNode::SetValue().
Referenced by tinyxml2::XMLUnknown::ShallowClone().
operator=()
void tinyxml2::XMLDocument::operator= (const XMLDocument &) [private]
Parse() [1/2]
 XMLError tinyxml2::XMLDocument::Parse (const char * xml, size_t nBytes = (size_t)(-1))
Parse an XML file from a character string. Returns XML_SUCCESS (0) on success, or an errorID.
You may optionally pass in the 'nBytes', which is the number of bytes which will be parsed. If not specified, TinyXML-2 will assume 'xml' points to a null terminated string.
Definition at line 2285 of file tinyxml2.cpp.
References _attributePool, _charBuffer, _commentPool, _elementPool, _errorID, _textPool, Clear(), tinyxml2::XMLNode::DeleteChildren(), Error(), Parse(), SetError(), TIXMLASSERT, and tinyxml2::XML_ERROR_EMPTY_DOCUMENT.
Parse() [2/2]
void tinyxml2::XMLDocument::Parse () [private]
Definition at line 2380 of file tinyxml2.cpp.
References _charBuffer, _parseCurLineNum, tinyxml2::XMLNode::_parseLineNum, _writeBOM, tinyxml2::XMLNode::NoChildren(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLUtil::ReadBOM(), SetError(), tinyxml2::XMLUtil::SkipWhiteSpace(), TIXMLASSERT, and tinyxml2::XML_ERROR_EMPTY_DOCUMENT.
Referenced by LoadFile(), and Parse().
PopDepth()
void tinyxml2::XMLDocument::PopDepth () [private]
Definition at line 2404 of file tinyxml2.cpp.
References _parsingDepth, and TIXMLASSERT.
Print()
void tinyxml2::XMLDocument::Print (XMLPrinter * streamer = 0) const
Print the Document. If the Printer is not provided, it will print to stdout. If you provide Printer, this can print to a file:
XMLPrinter printer( fp );
doc.Print( &printer );
Or you can use a printer to print to memory:
XMLPrinter printer;
doc.Print( &printer );
// printer.CStr() has a const char* to the XML
Definition at line 2316 of file tinyxml2.cpp.
References Accept().
Referenced by SaveFile().
PrintError()
void tinyxml2::XMLDocument::PrintError () const
A (trivial) utility function that prints the ErrorStr() to stdout.
Definition at line 2370 of file tinyxml2.cpp.
References ErrorStr().
ProcessEntities()
bool tinyxml2::XMLDocument::ProcessEntities () const [inline]
Definition at line 1725 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLText::ParseDeep(), and tinyxml2::XMLPrinter::VisitEnter().
PushDepth()
void tinyxml2::XMLDocument::PushDepth () [private]
Definition at line 2396 of file tinyxml2.cpp.
References _parseCurLineNum, _parsingDepth, SetError(), TINYXML2_MAX_ELEMENT_DEPTH, and tinyxml2::XML_ELEMENT_DEPTH_EXCEEDED.
Referenced by tinyxml2::XMLDocument::DepthTracker::DepthTracker().
RootElement() [1/2]
 XMLElement* tinyxml2::XMLDocument::RootElement () [inline]
Return the root element of DOM. Equivalent to FirstChildElement(). To get the first node, use FirstChild().
Definition at line 1747 of file tinyxml2.h.
RootElement() [2/2]
const XMLElement* tinyxml2::XMLDocument::RootElement () const [inline]
Definition at line 1750 of file tinyxml2.h.
SaveFile() [1/2]
 XMLError tinyxml2::XMLDocument::SaveFile (const char * filename, bool compact = false)
Save the XML file to disk. Returns XML_SUCCESS (0) on success, or an errorID.
Definition at line 2255 of file tinyxml2.cpp.
References _errorID, tinyxml2::callfopen(), SetError(), TIXMLASSERT, and tinyxml2::XML_ERROR_FILE_COULD_NOT_BE_OPENED.
SaveFile() [2/2]
 XMLError tinyxml2::XMLDocument::SaveFile (FILE * fp, bool compact = false)
Save the XML file to disk. You are responsible for providing and closing the FILE*.
Returns XML_SUCCESS (0) on success, or an errorID.
Definition at line 2274 of file tinyxml2.cpp.
References _errorID, ClearError(), and Print().
SetBOM()
void tinyxml2::XMLDocument::SetBOM (bool useBOM) [inline]
Sets whether to write the BOM when writing the file.
Definition at line 1740 of file tinyxml2.h.
SetError()
void tinyxml2::XMLDocument::SetError (XMLError error, int lineNum, const char * format, ...) [private]
Definition at line 2328 of file tinyxml2.cpp.
References _errorID, _errorLineNum, _errorStr, ErrorIDToName(), tinyxml2::StrPair::Reset(), tinyxml2::StrPair::SetStr(), TIXML_SNPRINTF, TIXML_VSNPRINTF, TIXMLASSERT, and tinyxml2::XML_ERROR_COUNT.
Referenced by LoadFile(), Parse(), tinyxml2::XMLElement::ParseAttributes(), tinyxml2::XMLNode::ParseDeep(), tinyxml2::XMLText::ParseDeep(), tinyxml2::XMLComment::ParseDeep(), tinyxml2::XMLDeclaration::ParseDeep(), tinyxml2::XMLUnknown::ParseDeep(), PushDepth(), and SaveFile().
ShallowClone()
virtual XMLNode* tinyxml2::XMLDocument::ShallowClone (XMLDocument * document) const [inline], [virtual]
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements tinyxml2::XMLNode .
Definition at line 1861 of file tinyxml2.h.
ShallowEqual()
virtual bool tinyxml2::XMLDocument::ShallowEqual (const XMLNode * compare) const [inline], [virtual]
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements tinyxml2::XMLNode .
Definition at line 1864 of file tinyxml2.h.
ToDocument() [1/2]
virtual XMLDocument* tinyxml2::XMLDocument::ToDocument () [inline], [virtual]
Safely cast to a Document, or null.
Reimplemented from tinyxml2::XMLNode .
Definition at line 1668 of file tinyxml2.h.
References TIXMLASSERT.
ToDocument() [2/2]
virtual const XMLDocument* tinyxml2::XMLDocument::ToDocument () const [inline], [virtual]
Reimplemented from tinyxml2::XMLNode .
Definition at line 1672 of file tinyxml2.h.
References TIXMLASSERT.
WhitespaceMode()
 Whitespace tinyxml2::XMLDocument::WhitespaceMode () const [inline]
Definition at line 1728 of file tinyxml2.h.
Referenced by tinyxml2::XMLText::ParseDeep().
Friends And Related Function Documentation
XMLComment
friend class XMLComment [friend]
Definition at line 1660 of file tinyxml2.h.
XMLDeclaration
friend class XMLDeclaration [friend]
Definition at line 1661 of file tinyxml2.h.
XMLElement
friend class XMLElement [friend]
Definition at line 1655 of file tinyxml2.h.
XMLNode
friend class XMLNode [friend]
Definition at line 1658 of file tinyxml2.h.
XMLText
friend class XMLText [friend]
Definition at line 1659 of file tinyxml2.h.
XMLUnknown
friend class XMLUnknown [friend]
Definition at line 1662 of file tinyxml2.h.
Member Data Documentation
_attributePool
 MemPoolT< sizeof(XMLAttribute) > tinyxml2::XMLDocument::_attributePool [private]
Definition at line 1890 of file tinyxml2.h.
Referenced by Clear(), tinyxml2::XMLElement::CreateAttribute(), and Parse().
_charBuffer
char* tinyxml2::XMLDocument::_charBuffer [private]
Definition at line 1878 of file tinyxml2.h.
Referenced by Clear(), LoadFile(), and Parse().
_commentPool
 MemPoolT< sizeof(XMLComment) > tinyxml2::XMLDocument::_commentPool [private]
Definition at line 1892 of file tinyxml2.h.
Referenced by Clear(), Identify(), NewComment(), NewDeclaration(), NewUnknown(), and Parse().
_elementPool
 MemPoolT< sizeof(XMLElement) > tinyxml2::XMLDocument::_elementPool [private]
Definition at line 1889 of file tinyxml2.h.
Referenced by Clear(), Identify(), NewElement(), and Parse().
_errorID
 XMLError tinyxml2::XMLDocument::_errorID [private]
Definition at line 1874 of file tinyxml2.h.
Referenced by ErrorName(), LoadFile(), Parse(), SaveFile(), and SetError().
_errorLineNum
int tinyxml2::XMLDocument::_errorLineNum [private]
Definition at line 1877 of file tinyxml2.h.
Referenced by SetError().
_errorNames
const char * tinyxml2::XMLDocument::_errorNames [static], [private]
Initial value:
= {
    "XML_SUCCESS",
    "XML_NO_ATTRIBUTE",
    "XML_WRONG_ATTRIBUTE_TYPE",
    "XML_ERROR_FILE_NOT_FOUND",
    "XML_ERROR_FILE_COULD_NOT_BE_OPENED",
    "XML_ERROR_FILE_READ_ERROR",
    "XML_ERROR_PARSING_ELEMENT",
    "XML_ERROR_PARSING_ATTRIBUTE",
    "XML_ERROR_PARSING_TEXT",
    "XML_ERROR_PARSING_CDATA",
    "XML_ERROR_PARSING_COMMENT",
    "XML_ERROR_PARSING_DECLARATION",
    "XML_ERROR_PARSING_UNKNOWN",
    "XML_ERROR_EMPTY_DOCUMENT",
    "XML_ERROR_MISMATCHED_ELEMENT",
    "XML_ERROR_PARSING",
    "XML_CAN_NOT_CONVERT_TEXT",
    "XML_NO_TEXT_NODE",
    "XML_ELEMENT_DEPTH_EXCEEDED"
}
Definition at line 1894 of file tinyxml2.h.
Referenced by ErrorIDToName().
_errorStr
 StrPair tinyxml2::XMLDocument::_errorStr [mutable], [private]
Definition at line 1876 of file tinyxml2.h.
Referenced by ErrorStr(), and SetError().
_parseCurLineNum
int tinyxml2::XMLDocument::_parseCurLineNum [private]
Definition at line 1879 of file tinyxml2.h.
Referenced by Identify(), Parse(), tinyxml2::XMLElement::ParseAttributes(), and PushDepth().
_parsingDepth
int tinyxml2::XMLDocument::_parsingDepth [private]
Definition at line 1880 of file tinyxml2.h.
Referenced by Clear(), PopDepth(), and PushDepth().
_processEntities
bool tinyxml2::XMLDocument::_processEntities [private]
Definition at line 1873 of file tinyxml2.h.
_textPool
 MemPoolT< sizeof(XMLText) > tinyxml2::XMLDocument::_textPool [private]
Definition at line 1891 of file tinyxml2.h.
Referenced by Clear(), Identify(), NewText(), and Parse().
_unlinked
 DynArray< XMLNode*, 10> tinyxml2::XMLDocument::_unlinked [private]
Definition at line 1887 of file tinyxml2.h.
Referenced by Clear(), CreateUnlinkedNode(), and MarkInUse().
_whitespaceMode
 Whitespace tinyxml2::XMLDocument::_whitespaceMode [private]
Definition at line 1875 of file tinyxml2.h.
_writeBOM
bool tinyxml2::XMLDocument::_writeBOM [private]
Definition at line 1872 of file tinyxml2.h.
Referenced by Parse().
The documentation for this class was generated from the following files:
include/ tinyxml2.h
src/ tinyxml2.cpp