MovableAgent Class Reference
#include <MovableAgent.h>
Public Member Functions
 MovableAgent (Map *m, long id, Point *initPosition, Clock *clock, double initSpeed)
virtual ~MovableAgent ()
string getName () override
string toString () override
virtual Point * move (MovementType type)=0
double getSpeed () const
void setSpeed (double speed)
Private Attributes
double m_speed
Detailed Description
Definition at line 24 of file MovableAgent.h.
Constructor & Destructor Documentation
MovableAgent()
MovableAgent::MovableAgent (Map * m, long id, Point * initPosition, Clock * clock, double initSpeed) [explicit]
Definition at line 16 of file MovableAgent.cpp.
~MovableAgent()
MovableAgent::~MovableAgent () [virtual]
Definition at line 21 of file MovableAgent.cpp.
Member Function Documentation
getName()
string MovableAgent::getName () [inline], [override], [virtual]
This function is used to get the name of the class. It is a pure virtual function, all subclasses implment it and return the actual name of the class.
Returns
the name of the class.
Reimplemented from LocatableAgent .
Reimplemented in Person , and Tablet .
Definition at line 31 of file MovableAgent.h.
getSpeed()
double MovableAgent::getSpeed () const
Definition at line 25 of file MovableAgent.cpp.
References m_speed.
Referenced by Person::randomWalk().
move()
virtual Point* MovableAgent::move (MovementType type) [pure virtual]
Implemented in Person , MobilePhone , and Tablet .
setSpeed()
void MovableAgent::setSpeed (double speed)
Definition at line 29 of file MovableAgent.cpp.
References m_speed.
Referenced by HoldableAgent::setHolder().
toString()
string MovableAgent::toString () [override], [virtual]
Builds a string with of the relevant information of the class. It is useful to output on the console or in a file the description of concrete agents.
Returns
a string representation of the class content. The values of the members are written in this string.
Reimplemented from LocatableAgent .
Reimplemented in Person , and Tablet .
Definition at line 33 of file MovableAgent.cpp.
References m_speed, and LocatableAgent::toString().
Referenced by HoldableAgent::toString(), and Person::toString().
Member Data Documentation
m_speed
double MovableAgent::m_speed [private]
Definition at line 44 of file MovableAgent.h.
Referenced by getSpeed(), setSpeed(), and toString().
The documentation for this class was generated from the following files:
include/ MovableAgent.h
src/ MovableAgent.cpp