World Class Reference
#include <World.h>
Public Member Functions
 World (Map *map, int numPersons, int numAntennas, int numMobilePhones)
 World (Map *map, int numPersons, const string &configAntennasFile, int numMobilePhones) noexcept(false)
 World (Map *map, const string &configPersonsFileName, const string &configAntennasFileName, const string &configSimulationFileName) noexcept(false)
virtual ~World ()
void runSimulation (string &personsFile, string &antennasFile) noexcept(false)
void dumpState ()
unsigned int getCurrentTime ()
 AgentsCollection * getAgents () const
void setAgents (AgentsCollection *agents)
 Clock * getClock () const
void setClock (Clock *clock)
 Map * getMap () const
void setMap (Map *map)
Private Member Functions
vector< Person * > generatePopulation (unsigned long numPersons)
vector< Person * > generatePopulation (unsigned long numPersons, vector< double > params, Person::AgeDistributions age_distribution, double male_share, double prob_mobile_phone, double speed_walk, double speed_car)
vector< Antenna * > generateAntennas (unsigned long numAntennas)
vector< Antenna * > parseAntennas (const string &configAntennasFile) noexcept(false)
vector< Person * > parsePersons (const string &personsFileName) noexcept(false)
vector< MobilePhone * > generateMobilePhones (int numMobilePhones, HoldableAgent::CONNECTION_TYPE connType)
void parseSimulationFile (const string &configSimulationFileName) noexcept(false)
Private Attributes
 Map * m_map
 AgentsCollection * m_agentsCollection
 Clock * m_clock
unsigned long m_startTime
unsigned long m_endTime
unsigned long m_timeIncrement
 HoldableAgent::CONNECTION_TYPE m_connType
 MovementType m_mvType
Detailed Description
Definition at line 28 of file World.h.
Constructor & Destructor Documentation
World() [1/3]
World::World (Map * map, int numPersons, int numAntennas, int numMobilePhones)
Default constructor
Definition at line 37 of file World.cpp.
References AgentsCollection::addAgent(), EMField::addAntenna(), generateAntennas(), generateMobilePhones(), generatePopulation(), EMField::instance(), m_agentsCollection, m_clock, m_connType, m_mvType, and RANDOM_WALK.
World() [2/3]
World::World (Map * map, int numPersons, const string & configAntennasFile, int numMobilePhones) [noexcept]
Definition at line 61 of file World.cpp.
References AgentsCollection::addAgent(), EMField::addAntenna(), generateMobilePhones(), generatePopulation(), EMField::instance(), m_agentsCollection, m_clock, m_connType, m_mvType, parseAntennas(), and RANDOM_WALK.
World() [3/3]
World::World (Map * map, const string & configPersonsFileName, const string & configAntennasFileName, const string & configSimulationFileName) [noexcept]
Definition at line 84 of file World.cpp.
References AgentsCollection::addAgent(), EMField::addAntenna(), EMField::instance(), m_agentsCollection, m_clock, m_endTime, m_startTime, m_timeIncrement, parseAntennas(), parsePersons(), and parseSimulationFile().
~World()
World::~World () [virtual]
Default destructor
Definition at line 104 of file World.cpp.
References m_agentsCollection, and m_clock.
Member Function Documentation
dumpState()
void World::dumpState ()
generateAntennas()
vector< Antenna * > World::generateAntennas (unsigned long numAntennas) [private]
Definition at line 208 of file World.cpp.
References Constants::ANTENNA_POWER, Constants::ATT_FACTOR, utils::generatePoints(), getMap(), IDGenerator::instance(), m_clock, Constants::MAX_CONNECTIONS, IDGenerator::next(), OMNIDIRECTIONAL, Constants::S_MID, and Constants::S_STEEP.
Referenced by World().
generateMobilePhones()
vector< MobilePhone * > World::generateMobilePhones (int numMobilePhones, HoldableAgent::CONNECTION_TYPE connType) [private]
Definition at line 228 of file World.cpp.
References AgentsCollection::addAgent(), getMap(), IDGenerator::instance(), m_agentsCollection, m_clock, IDGenerator::next(), Constants::POWER_THRESHOLD, and Constants::QUALITY_THRESHOLD.
Referenced by generatePopulation(), and World().
generatePopulation() [1/2]
vector< Person * > World::generatePopulation (unsigned long numPersons) [private]
Definition at line 189 of file World.cpp.
References RandomNumberGenerator::generateNormal2Double(), utils::generatePoints(), RandomNumberGenerator::generateUniformInt(), getMap(), IDGenerator::instance(), RandomNumberGenerator::instance(), m_clock, and IDGenerator::next().
Referenced by parsePersons(), and World().
generatePopulation() [2/2]
vector< Person * > World::generatePopulation (unsigned long numPersons, vector< double > params, Person::AgeDistributions age_distribution, double male_share, double prob_mobile_phone, double speed_walk, double speed_car) [private]
Definition at line 364 of file World.cpp.
References Person::addDevice(), RandomNumberGenerator::generateBinomialInt(), generateMobilePhones(), RandomNumberGenerator::generateNormalDouble(), utils::generatePoints(), RandomNumberGenerator::generateTruncatedNormalDouble(), RandomNumberGenerator::generateUniformDouble(), getMap(), IDGenerator::instance(), RandomNumberGenerator::instance(), m_clock, m_connType, and IDGenerator::next().
getAgents()
 AgentsCollection * World::getAgents () const
Definition at line 165 of file World.cpp.
References m_agentsCollection.
getClock()
 Clock * World::getClock () const
Definition at line 173 of file World.cpp.
References m_clock.
Referenced by runSimulation().
getCurrentTime()
unsigned int World::getCurrentTime ()
Definition at line 161 of file World.cpp.
References Clock::getCurrentTime(), and m_clock.
getMap()
 Map * World::getMap () const
Definition at line 181 of file World.cpp.
References m_map.
Referenced by generateAntennas(), generateMobilePhones(), generatePopulation(), and parseAntennas().
parseAntennas()
vector< Antenna * > World::parseAntennas (const string & configAntennasFile) [private], [noexcept]
Definition at line 240 of file World.cpp.
References tinyxml2::XMLNode::FirstChildElement(), utils::getFirstChildElement(), getMap(), IDGenerator::instance(), tinyxml2::XMLDocument::LoadFile(), m_clock, tinyxml2::XMLElement::Name(), IDGenerator::next(), tinyxml2::XMLNode::NextSiblingElement(), and tinyxml2::XML_SUCCESS.
Referenced by World().
parsePersons()
vector< Person * > World::parsePersons (const string & personsFileName) [private], [noexcept]
Definition at line 265 of file World.cpp.
References tinyxml2::XMLNode::FirstChildElement(), generatePopulation(), utils::getFirstChildElement(), utils::getNode(), tinyxml2::XMLDocument::LoadFile(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), and tinyxml2::XML_SUCCESS.
Referenced by World().
parseSimulationFile()
void World::parseSimulationFile (const string & configSimulationFileName) [private], [noexcept]
Definition at line 331 of file World.cpp.
References tinyxml2::XMLNode::FirstChildElement(), utils::getNode(), tinyxml2::XMLDocument::LoadFile(), m_connType, m_endTime, m_mvType, m_startTime, m_timeIncrement, RANDOM_WALK, tinyxml2::XMLNode::ToText(), UNKNOWN, tinyxml2::XMLNode::Value(), and tinyxml2::XML_SUCCESS.
Referenced by World().
runSimulation()
void World::runSimulation (string & personsFile, string & antennasFile) [noexcept]
Definition at line 111 of file World.cpp.
References Person::dumpDevices(), LocatableAgent::dumpLocation(), AgentsCollection::getAgentListByType(), getClock(), Clock::getFinalTime(), Clock::getInitialTime(), m_agentsCollection, m_clock, m_mvType, Person::move(), Clock::realTime(), and Clock::tick().
setAgents()
void World::setAgents (AgentsCollection * agents)
Definition at line 169 of file World.cpp.
References m_agentsCollection.
setClock()
void World::setClock (Clock * clock)
Definition at line 177 of file World.cpp.
References m_clock.
setMap()
void World::setMap (Map * map)
Definition at line 185 of file World.cpp.
References m_map.
Member Data Documentation
m_agentsCollection
 AgentsCollection* World::m_agentsCollection [private]
Definition at line 60 of file World.h.
Referenced by generateMobilePhones(), getAgents(), runSimulation(), setAgents(), World(), and ~World().
m_clock
 Clock* World::m_clock [private]
Definition at line 61 of file World.h.
Referenced by generateAntennas(), generateMobilePhones(), generatePopulation(), getClock(), getCurrentTime(), parseAntennas(), runSimulation(), setClock(), World(), and ~World().
m_connType
 HoldableAgent::CONNECTION_TYPE World::m_connType [private]
Definition at line 66 of file World.h.
Referenced by generatePopulation(), parseSimulationFile(), and World().
m_endTime
unsigned long World::m_endTime [private]
Definition at line 63 of file World.h.
Referenced by parseSimulationFile(), and World().
m_map
 Map* World::m_map [private]
Definition at line 58 of file World.h.
Referenced by getMap(), and setMap().
m_mvType
 MovementType World::m_mvType [private]
Definition at line 67 of file World.h.
Referenced by parseSimulationFile(), runSimulation(), and World().
m_startTime
unsigned long World::m_startTime [private]
Definition at line 62 of file World.h.
Referenced by parseSimulationFile(), and World().
m_timeIncrement
unsigned long World::m_timeIncrement [private]
Definition at line 64 of file World.h.
Referenced by parseSimulationFile(), and World().
The documentation for this class was generated from the following files:
include/ World.h
src/ World.cpp