Antenna Class Reference
#include <Antenna.h>
Public Member Functions
 Antenna (Map *m, long id, Point *initPosition, Clock *clock, double attenuationFactor, double power, unsigned long maxConnections, double smid, double ssteep, AntennaType type)
 Antenna (Map *m, Clock *clock, long id, XMLElement *el)
virtual ~Antenna ()
string getName () override
string toString () override
double getAttenuationFactor () const
void setAttenuationFactor (double attenuationFactor)
double getPower () const
void setPower (double power)
unsigned long getMaxConnections () const
void setMaxConnections (int maxConnections)
bool tryRegisterDevice (HoldableAgent *device)
void attachDevice (HoldableAgent *device)
void dettachDevice (HoldableAgent *device)
 AntennaType getType () const
void setType (AntennaType type)
double S (double dist) const
double squality (Point p) const
double getSmid () const
void setSmid (double smid)
double getSSteep () const
void setSSteep (double sSteep)
double computeSignalQuality (Point *p) const
double computePower (Point *p) const
Private Member Functions
bool alreadyRegistered (HoldableAgent *ag)
void registerEvent (HoldableAgent *ag, EventType event, bool verbose)
unsigned long getNumActiveConections ()
double S0 ()
double SDist (double dist)
Private Attributes
double m_attenuationFactor
double m_power
unsigned long m_maxConnections
double m_Smid
double m_SSteep
Polygon * m_cell
vector< HoldableAgent * > m_devices
 AntennaType m_type
ofstream m_file
Detailed Description
This class simulates an antenna of the mobile phone network.
Definition at line 29 of file Antenna.h.
Constructor & Destructor Documentation
Antenna() [1/2]
Antenna::Antenna (Map * m, long id, Point * initPosition, Clock * clock, double attenuationFactor, double power, unsigned long maxConnections, double smid, double ssteep, AntennaType type) [explicit]
Constructor of the class. It builds an object providing directly the values for each parameter of the antenna.
Parameters
m a pointer to the Map object used for the simulation
id the id of the Antenna
initPosition the position of the antenna on the map
clock a pointer to the Clock object used for the simulation
attenuationFactor the attenuation factor of the surrounding environment. In real life, it takes values between 2 (in open field) and 6 (inside buildings).
power the power of the antenna in Watts.
maxConnections the maximum number of the connections that the antenna can accept.
smid is a parameter of an antenna. The significance of this parameter is described in mobloc R package.
ssteep is a parameter of an antenna. The significance of this parameter is described in mobloc R package.
type it could have two values AntennaType::OMNIDIRECTIONAL for omnidirectional antennas and AntennaType::DIRECTIONAL for directional antennas.
Definition at line 20 of file Antenna.cpp.
Antenna() [2/2]
Antenna::Antenna (Map * m, Clock * clock, long id, XMLElement * el) [explicit]
Constructor of the class. It builds an object taking the value of the parameters from an XML Element, usually when an Antenna object is built reading the xml configuration file.
Parameters
m a pointer to the Map object used for the simulation
clock a pointer to the Clock object used for the simulation
id the id of the Antenna
el the XML Element containing the parameters of the Antenna.
Definition at line 37 of file Antenna.cpp.
References DIRECTIONAL, Map::getGlobalFactory(), Agent::getMap(), getName(), utils::getNode(), m_attenuationFactor, m_cell, m_file, m_maxConnections, m_power, m_Smid, m_SSteep, m_type, OMNIDIRECTIONAL, LocatableAgent::setLocation(), tinyxml2::XMLNode::ToText(), tinyxml2::XMLNode::Value(), and Rtnorm::x.
~Antenna()
Antenna::~Antenna () [virtual]
Destructor of the class. It closes the file where the Antenna dumps the registered events during the simulation.
Definition at line 77 of file Antenna.cpp.
References m_file.
Member Function Documentation
alreadyRegistered()
bool Antenna::alreadyRegistered (HoldableAgent * ag) [private]
Definition at line 153 of file Antenna.cpp.
References m_devices.
Referenced by tryRegisterDevice().
attachDevice()
void Antenna::attachDevice (HoldableAgent * device)
Connects a new mobile device and outputs an event EventType::ATTACH_DEVICE in the output file. Internally, the antenna keeps a vector with all connected mobile devices. devices. When a new mobile device is connected it is added to this vector.
Parameters
device a pointer to the object that represents the mobile device connected to this antenna.
Definition at line 138 of file Antenna.cpp.
References ATTACH_DEVICE, m_devices, and registerEvent().
Referenced by tryRegisterDevice().
computePower()
double Antenna::computePower (Point * p) const
Computes the power of the signal given by an antenna in a certain location.
Parameters
p the location where we want to compute the power of the signal.
Returns
the power of the signal in the location given by Point p.
Definition at line 262 of file Antenna.cpp.
References LocatableAgent::getLocation(), m_attenuationFactor, m_power, m_type, and OMNIDIRECTIONAL.
Referenced by EMField::isAntennaInRange().
computeSignalQuality()
double Antenna::computeSignalQuality (Point * p) const
Computes the signal quality given by an antenna in a certain location.
Parameters
p the location where we want to compute the signal quality.
Returns
the signal quality.
Definition at line 253 of file Antenna.cpp.
References LocatableAgent::getLocation(), m_Smid, m_SSteep, m_type, OMNIDIRECTIONAL, and S().
Referenced by EMField::connectionLikelihood(), and EMField::isAntennaInRange().
dettachDevice()
void Antenna::dettachDevice (HoldableAgent * device)
Disconnects a mobile device from the antenna and outputs an event EventType::DEATACH_DEVICE in the output file. Internally, the mobile device is removed from the vector of the connected mobile devices.
Parameters
device
Definition at line 144 of file Antenna.cpp.
References DETACH_DEVICE, m_devices, and registerEvent().
Referenced by MobilePhone::tryConnectNaiveAlgorithm().
getAttenuationFactor()
double Antenna::getAttenuationFactor () const
Returns the surrounding environment' attenuation factor of the signal.
Returns
the signals' attenuation factor of the surrounding environment. In real life, it takes values between 2 (in open field) and 6 (inside buildings).
Definition at line 88 of file Antenna.cpp.
References m_attenuationFactor.
getMaxConnections()
unsigned long Antenna::getMaxConnections () const
Returns the maximum number of mobile devices that an antenna can connect.
Definition at line 110 of file Antenna.cpp.
References m_maxConnections.
getName()
string Antenna::getName () [inline], [override], [virtual]
Overrides the same method from the superclass.
Returns
the name of the class, i.e. `Antenna`
Implements Agent .
Definition at line 71 of file Antenna.h.
Referenced by Antenna().
getNumActiveConections()
unsigned long Antenna::getNumActiveConections () [private]
Definition at line 169 of file Antenna.cpp.
References m_devices.
Referenced by tryRegisterDevice().
getPower()
double Antenna::getPower () const
Returns the power of an antenna in Watts at the location of antenna. This power decreases with a power of the distance from antenna.
Returns
the power of an antenna in Watts.
Definition at line 102 of file Antenna.cpp.
References m_power.
getSmid()
double Antenna::getSmid () const
Returns the value of the Smid antenna parameter.
Returns
the value of the Smid antenna parameter.
Definition at line 237 of file Antenna.cpp.
References m_Smid.
getSSteep()
double Antenna::getSSteep () const
Returns the value of the Ssteep antenna parameter.
Returns
the value of the Ssteep antenna parameter.
Definition at line 245 of file Antenna.cpp.
References m_SSteep.
getType()
 AntennaType Antenna::getType () const
Returns the antenna type: omnidirectional or directional
Returns
the antenna type : AntennaType::OMNIDIRECTIONAL or AntennaType::DIRECTIONAL.
Definition at line 161 of file Antenna.cpp.
References m_type.
registerEvent()
void Antenna::registerEvent (HoldableAgent * ag, EventType event, bool verbose) [private]
Definition at line 173 of file Antenna.cpp.
References ALREADY_ATTACHED_DEVICE, ATTACH_DEVICE, DETACH_DEVICE, Agent::getClock(), Clock::getCurrentTime(), Agent::getId(), LocatableAgent::getLocation(), IN_RANGE_NOT_ATTACHED_DEVICE, m_file, and Constants::sep.
Referenced by attachDevice(), dettachDevice(), and tryRegisterDevice().
S()
double Antenna::S (double dist) const
Computes the signal strength at the distance dist from antenna location.
Parameters
dist the distance from antenna location.
Returns
the signal strength.
Definition at line 230 of file Antenna.cpp.
References m_type, OMNIDIRECTIONAL, S0(), and SDist().
Referenced by computeSignalQuality().
S0()
double Antenna::S0 () [private]
Definition at line 222 of file Antenna.cpp.
References m_power.
Referenced by S().
SDist()
double Antenna::SDist (double dist) [private]
Definition at line 226 of file Antenna.cpp.
References m_attenuationFactor.
Referenced by S().
setAttenuationFactor()
void Antenna::setAttenuationFactor (double attenuationFactor)
Sets the surrounding environment' attenuation factor of the signal for an antenna.
Parameters
attenuationFactor the value of the surrounding environment' attenuation factor of the signal. In real life, it takes values between 2 (in open field) and 6 (inside buildings).
Definition at line 92 of file Antenna.cpp.
References m_attenuationFactor.
setMaxConnections()
void Antenna::setMaxConnections (int maxConnections)
Sets the number of mobile devices that an antenna can connect.
Parameters
maxConnections the number of mobile devices that an antenna can connect.
Definition at line 114 of file Antenna.cpp.
References m_maxConnections.
setPower()
void Antenna::setPower (double power)
Sets the power of an antenna.
Parameters
power the value of the antenna's power.
Definition at line 106 of file Antenna.cpp.
References m_power.
setSmid()
void Antenna::setSmid (double smid)
Sets the value of the Smid antenna parameter.
Parameters
smid the value of the Smid antenna parameter.
Definition at line 241 of file Antenna.cpp.
References m_Smid.
setSSteep()
void Antenna::setSSteep (double sSteep)
Sets the value of the Ssteep antenna parameter.
Parameters
smid the value of the Ssteep antenna parameter.
Definition at line 249 of file Antenna.cpp.
References m_SSteep.
setType()
void Antenna::setType (AntennaType type)
Sets the antenna type.
Parameters
type the antenna type. It could take the following two values: AntennaType::OMNIDIRECTIONAL or AntennaType::DIRECTIONAL.
Definition at line 165 of file Antenna.cpp.
References m_type.
squality()
double Antenna::squality (Point p) const
Computes the signal quality of the signal given by an antenna in a certain location.
Parameters
p the location where we want to compute the signal quality.
Returns
toString()
string Antenna::toString () [override], [virtual]
Overrides the same method from the superclass. It is used to write the characteristics of the Antenna in a file or console.
Returns
a string that describes the parameters of the Antenna.
Implements Agent .
Definition at line 96 of file Antenna.cpp.
References m_attenuationFactor, m_maxConnections, m_power, and ImmovableAgent::toString().
tryRegisterDevice()
bool Antenna::tryRegisterDevice (HoldableAgent * device)
Tries to register a mobile device as being connected to this antenna.
Parameters
device a pointer to the object that represents a mobile device.
Returns
true if the connection is succesful, false otherwise.
Definition at line 118 of file Antenna.cpp.
References ALREADY_ATTACHED_DEVICE, alreadyRegistered(), attachDevice(), getNumActiveConections(), IN_RANGE_NOT_ATTACHED_DEVICE, m_maxConnections, and registerEvent().
Member Data Documentation
m_attenuationFactor
double Antenna::m_attenuationFactor [private]
Definition at line 215 of file Antenna.h.
Referenced by Antenna(), computePower(), getAttenuationFactor(), SDist(), setAttenuationFactor(), and toString().
m_cell
Polygon* Antenna::m_cell [private]
Definition at line 221 of file Antenna.h.
Referenced by Antenna().
m_devices
vector< HoldableAgent*> Antenna::m_devices [private]
Definition at line 222 of file Antenna.h.
Referenced by alreadyRegistered(), attachDevice(), dettachDevice(), and getNumActiveConections().
m_file
ofstream Antenna::m_file [private]
Definition at line 224 of file Antenna.h.
Referenced by Antenna(), registerEvent(), and ~Antenna().
m_maxConnections
unsigned long Antenna::m_maxConnections [private]
Definition at line 217 of file Antenna.h.
Referenced by Antenna(), getMaxConnections(), setMaxConnections(), toString(), and tryRegisterDevice().
m_power
double Antenna::m_power [private]
Definition at line 216 of file Antenna.h.
Referenced by Antenna(), computePower(), getPower(), S0(), setPower(), and toString().
m_Smid
double Antenna::m_Smid [private]
Definition at line 218 of file Antenna.h.
Referenced by Antenna(), computeSignalQuality(), getSmid(), and setSmid().
m_SSteep
double Antenna::m_SSteep [private]
Definition at line 219 of file Antenna.h.
Referenced by Antenna(), computeSignalQuality(), getSSteep(), and setSSteep().
m_type
 AntennaType Antenna::m_type [private]
Definition at line 223 of file Antenna.h.
Referenced by Antenna(), computePower(), computeSignalQuality(), getType(), S(), and setType().
The documentation for this class was generated from the following files:
include/ Antenna.h
src/ Antenna.cpp