utils Namespace Reference
Functions
vector< Point * > generatePoints (Map *m, int n)
void printPersonHeader ()
void printAntennaHeader ()
void printPhoneHeader ()
const char * getAntennasFile (int argc, char **argv)
 XMLNode * getNode (XMLElement *el, const char *name)
 XMLElement * getFirstChildElement (XMLElement *el, const char *name) noexcept(false)
Variables
const double PI = std::atan(1.0) * 4
Function Documentation
generatePoints()
vector< Point * > utils::generatePoints (Map * m, int n)
Definition at line 26 of file Utils.cpp.
References RandomNumberGenerator::generateUniformDouble(), Map::getBoundary(), Map::getGlobalFactory(), RandomNumberGenerator::instance(), and Rtnorm::x.
Referenced by World::generateAntennas(), and World::generatePopulation().
getAntennasFile()
const char* utils::getAntennasFile (int argc, char ** argv)
getFirstChildElement()
 XMLElement * utils::getFirstChildElement (XMLElement * el, const char * name) [noexcept]
Definition at line 72 of file Utils.cpp.
References tinyxml2::XMLNode::FirstChildElement().
Referenced by World::parseAntennas(), and World::parsePersons().
getNode()
 XMLNode * utils::getNode (XMLElement * el, const char * name)
Definition at line 65 of file Utils.cpp.
References tinyxml2::XMLNode::FirstChild(), and tinyxml2::XMLNode::FirstChildElement().
Referenced by Antenna::Antenna(), World::parsePersons(), and World::parseSimulationFile().
printAntennaHeader()
void utils::printAntennaHeader ()
Definition at line 55 of file Utils.cpp.
printPersonHeader()
void utils::printPersonHeader ()
Definition at line 50 of file Utils.cpp.
printPhoneHeader()
void utils::printPhoneHeader ()
Definition at line 60 of file Utils.cpp.
Variable Documentation
PI
const double utils::PI = std::atan(1.0) * 4
Definition at line 31 of file Utils.h.
Referenced by Person::randomWalk().