.TH "It" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
It
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Subclass of the truncated normal distribution\&.
.PP
Subclass of the uniform distribution\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
