.TH "include/AgentsCollection.h" 3 "Wed Oct 30 2019" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/AgentsCollection.h
.SH SYNOPSIS
.br
.PP
\fC#include <Agent\&.h>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAgentsCollection\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unordered_multimap< string, \fBAgent\fP * >::iterator \fBum_iterator\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unordered_multimap<string, \fBAgent\fP*>::iterator \fBum_iterator\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
