.TH "include/parsers/AntennaConfigParser.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/parsers/AntennaConfigParser.h
.SH SYNOPSIS
.br
.PP
\fC#include <agent/Antenna\&.h>\fP
.br
\fC#include <agent/AgentsCollection\&.h>\fP
.br
\fC#include <events/EventFactory\&.h>\fP
.br
\fC#include <parsers/ConfigParser\&.h>\fP
.br
\fC#include <parsers/SimulationConfiguration\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAntennaConfigParser\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
