.TH "include/AntennaType.h" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/AntennaType.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAntennaType\fP { \fBAntennaType::OMNIDIRECTIONAL\fP, \fBAntennaType::DIRECTIONAL\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAntennaType\fP\fC [strong]\fP"
An enum class that is used to represent the type of an antenna\&. There are two types of antennas supported: omnidirectional and directional\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOMNIDIRECTIONAL \fP\fP
.TP
\fB\fIDIRECTIONAL \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
