.TH "include/agent/Antenna.h" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/agent/Antenna.h
.SH SYNOPSIS
.br
.PP
\fC#include <agent/HoldableAgent\&.h>\fP
.br
\fC#include <agent/ImmovableAgent\&.h>\fP
.br
\fC#include <agent/MobileOperator\&.h>\fP
.br
\fC#include <AntennaType\&.h>\fP
.br
\fC#include <EventType\&.h>\fP
.br
\fC#include <geos/geom/Coordinate\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAntenna\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtinyxml2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
