.TH "include/events/CellIDEvent.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/events/CellIDEvent.h
.SH SYNOPSIS
.br
.PP
\fC#include <events/Event\&.h>\fP
.br
\fC#include <events/EventConfig\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCellIDEvent\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
