.TH "include/events/CellIDTAEventConfig.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/events/CellIDTAEventConfig.h
.SH SYNOPSIS
.br
.PP
\fC#include <events/CellIDEventConfig\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCellIDTAEventConfig\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
