.TH "include/CSVparser.hpp" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CSVparser.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <list>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.ti -1c
.RI "class \fBCSVParser\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDataType\fP { \fBeFILE\fP = 0, \fBePURE\fP = 1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDataType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIeFILE \fP\fP
.TP
\fB\fIePURE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
