.TH "Displace" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Displace
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Displace\&.h>\fP
.PP
Inherited by \fBHomeWorkDisplacement\fP, \fBLevyFlightDisplacement\fP, \fBRandomWalkDisplacement\fP, and \fBRandomWalkDriftDisplacement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplace\fP (\fBSimulationConfiguration\fP *simconfig, double speed)"
.br
.ti -1c
.RI "virtual \fB~Displace\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements a Strategy design pattern\&. It acts as an interface to different displacement algorithms\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Displace::Displace (\fBSimulationConfiguration\fP * simconfig, double speed)"
Constructor of the class\&. Initializes members\&. 
.PP
\fBParameters\fP
.RS 4
\fIspeed\fP the speed of displacement\&. 
.RE
.PP

.SS "virtual Displace::~Displace ()\fC [virtual]\fP"
Default destructor\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
