.TH "include/DistributionType.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/DistributionType.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDistributionType\fP { \fBDistributionType::LAPLACE\fP, \fBDistributionType::UNIFORM\fP, \fBDistributionType::NORMAL\fP, \fBDistributionType::TRUNCATED_NORMAL\fP, \fBDistributionType::LEVY\fP, \fBDistributionType::EXPONENTIAL\fP, \fBDistributionType::BINOMIAL\fP, \fBDistributionType::BERNOULLI\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDistributionType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILAPLACE \fP\fP
.TP
\fB\fIUNIFORM \fP\fP
.TP
\fB\fINORMAL \fP\fP
.TP
\fB\fITRUNCATED_NORMAL \fP\fP
.TP
\fB\fILEVY \fP\fP
.TP
\fB\fIEXPONENTIAL \fP\fP
.TP
\fB\fIBINOMIAL \fP\fP
.TP
\fB\fIBERNOULLI \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
