.TH "Event" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Event\&.h>\fP
.PP
Inherited by \fBCellIDEvent\fP, and \fBCellIDTAEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const string \fBtoString\fP ()=0"
.br
.ti -1c
.RI "virtual \fBEventConfig\fP * \fBgetEventConfig\fP ()=0"
.br
.ti -1c
.RI "virtual \fB~Event\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the interface of an event object\&. All types of events should implement the functions declared here\&. An \fBEvent\fP object is to be created by the \fBEventFactory\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Event::~Event ()\fC [virtual]\fP"
Default destructor\&. 
.SS "Event::Event ()\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBEventConfig\fP* Event::getEventConfig ()\fC [pure virtual]\fP"
Returns a pointer to the \fBEventConfig\fP object used to create the \fBEvent\fP object by the factory method\&. return a pointer to the \fBEventConfig\fP object used to create the \fBEvent\fP object by the factory method\&. 
.PP
Implemented in \fBCellIDTAEvent\fP, and \fBCellIDEvent\fP\&.
.SS "virtual const string Event::toString ()\fC [pure virtual]\fP"
Returns the string representation of an \fBEvent\fP object\&. 
.PP
\fBReturns\fP
.RS 4
the string representation of an \fBEvent\fP object\&. The content of the string depends on the concrete type of the event\&. 
.RE
.PP

.PP
Implemented in \fBCellIDTAEvent\fP, and \fBCellIDEvent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
