.TH "include/events/EventType.h" 3 "Wed May 19 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/events/EventType.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEventType\fP { \fBEventType::CELLID\fP, \fBEventType::CELLIDTA\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBEventType\fP\fC [strong]\fP"
This class is an enumeration of network events currently registered: 
.PD 0

.IP "\(bu" 2
CELLID this event contains the timestamp, cell ID, device ID, event code and network type\&. 
.IP "\(bu" 2
CELLIDTA this event contains the timestamp, cell ID, device ID, event code, network type, and timing advance\&. 
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICELLID \fP\fP
.TP
\fB\fICELLIDTA \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
