.TH "EventConfig" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventConfig
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EventConfig\&.h>\fP
.PP
Inherited by \fBCellIDEventConfig\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventConfig\fP ()"
.br
.ti -1c
.RI "virtual const unsigned long \fBgetCellID\fP ()=0"
.br
.ti -1c
.RI "virtual const unsigned long \fBgetDeviceID\fP ()=0"
.br
.ti -1c
.RI "virtual const unsigned long \fBgetTimestamp\fP ()=0"
.br
.ti -1c
.RI "virtual const \fBEventCode\fP \fBgetEventCode\fP ()=0"
.br
.ti -1c
.RI "virtual const \fBNetworkType\fP \fBgetNetworkType\fP ()=0"
.br
.ti -1c
.RI "virtual \fB~EventConfig\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the base class of the \fBEventConfig\fP objects\&. It defines the interface that all derived classes should implement\&. An \fBEventConfig\fP object is used by the \fBEventFactory\fP to build a specific \fBEvent\fP object and it contains the parameters of the specific event\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EventConfig::EventConfig ()"
Default constructor\&. 
.SS "virtual EventConfig::~EventConfig ()\fC [virtual]\fP"
Default destructor 
.SH "Member Function Documentation"
.PP 
.SS "virtual const unsigned long EventConfig::getCellID ()\fC [pure virtual]\fP"
This is a pure virtual method that should be implemented by all derived classes\&. It returns the ID of the cell where the event was recorded by the network\&. 
.PP
\fBReturns\fP
.RS 4
the ID of the cell where the event was recorded by the network\&. 
.RE
.PP

.PP
Implemented in \fBCellIDEventConfig\fP\&.
.SS "virtual const unsigned long EventConfig::getDeviceID ()\fC [pure virtual]\fP"
This is a pure virtual method that should be implemented by all derived classes\&. It returns the ID of the device that generated the event recorded by the network\&. 
.PP
\fBReturns\fP
.RS 4
the ID of the device that generated the event recorded by the network\&. 
.RE
.PP

.PP
Implemented in \fBCellIDEventConfig\fP\&.
.SS "virtual const \fBEventCode\fP EventConfig::getEventCode ()\fC [pure virtual]\fP"
This is a pure virtual method that should be implemented by all derived classes\&. It returns the type of the event recorded by the network\&. 
.PP
\fBReturns\fP
.RS 4
one of the following values defined in the EventCode class: 
.PD 0

.IP "\(bu" 2
ATTACH_DEVICE 
.IP "\(bu" 2
DETACH_DEVICE 
.IP "\(bu" 2
ALREADY_ATTACHED_DEVICE 
.IP "\(bu" 2
IN_RANGE_NOT_ATTACHED_DEVICE 
.PP
.RE
.PP

.PP
Implemented in \fBCellIDEventConfig\fP\&.
.SS "virtual const \fBNetworkType\fP EventConfig::getNetworkType ()\fC [pure virtual]\fP"
This is a pure virtual method that should be implemented by all derived classes\&. It returns the type the network\&. 
.PP
\fBReturns\fP
.RS 4
the type of the network: 
.PD 0

.IP "\(bu" 2
\fBNetworkType::_3G\fP 
.IP "\(bu" 2
\fBNetworkType::_4G\fP\&. 
.PP
.RE
.PP

.PP
Implemented in \fBCellIDEventConfig\fP\&.
.SS "virtual const unsigned long EventConfig::getTimestamp ()\fC [pure virtual]\fP"
This is a pure virtual method that should be implemented by all derived classes\&. It returns the time when the event was recorded by the network\&. 
.PP
\fBReturns\fP
.RS 4
the time (measured by the simulation clock) when the event was recorded by the network\&. 
.RE
.PP

.PP
Implemented in \fBCellIDEventConfig\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
