.TH "include/HomeWorkState.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/HomeWorkState.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHomeWorkState\fP { \fBHomeWorkState::STAY_HOME\fP, \fBHomeWorkState::GO_WORK\fP, \fBHomeWorkState::STAY_WORK\fP, \fBHomeWorkState::GO_ANCHOR\fP, \fBHomeWorkState::STAY_ANCHOR\fP, \fBHomeWorkState::GO_HOME\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHomeWorkState\fP\fC [strong]\fP"
This class is an enumeration of states of a person in a home-work simulation scenario: STAY_HOME GO_WORK STAY_WORK GO_HOME 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTAY_HOME \fP\fP
.TP
\fB\fIGO_WORK \fP\fP
.TP
\fB\fISTAY_WORK \fP\fP
.TP
\fB\fIGO_ANCHOR \fP\fP
.TP
\fB\fISTAY_ANCHOR \fP\fP
.TP
\fB\fIGO_HOME \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
