.TH "HomeWorkScenario" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeWorkScenario
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HomeWorkScenario\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHomeWorkScenario\fP ()"
.br
.ti -1c
.RI "virtual \fB~HomeWorkScenario\fP ()"
.br
.ti -1c
.RI "void \fBaddHomeLocation\fP (\fBHomeWorkLocation\fP h)"
.br
.ti -1c
.RI "void \fBaddWorkLocation\fP (\fBHomeWorkLocation\fP h)"
.br
.ti -1c
.RI "void \fBaddAnchorLocation\fP (\fBHomeWorkLocation\fP h)"
.br
.ti -1c
.RI "vector< \fBHomeWorkLocation\fP > \fBgetHomeLocations\fP () const"
.br
.ti -1c
.RI "vector< \fBHomeWorkLocation\fP > \fBgetWorkLocations\fP () const"
.br
.ti -1c
.RI "vector< \fBHomeWorkLocation\fP > \fBgetAnchorLocations\fP () const"
.br
.ti -1c
.RI "double \fBgetPrecentTimeHome\fP () const"
.br
.ti -1c
.RI "void \fBsetPrecentTimeHome\fP (double precentTimeHome)"
.br
.ti -1c
.RI "double \fBgetPrecentTimeWork\fP () const"
.br
.ti -1c
.RI "void \fBsetPrecentTimeWork\fP (double precentTimeWork)"
.br
.ti -1c
.RI "double \fBgetPrecentTimeTravel\fP () const"
.br
.ti -1c
.RI "void \fBsetPrecentTimeTravel\fP (double precentTimetravel)"
.br
.ti -1c
.RI "double \fBgetPrecentTimeAnchorPoint\fP () const"
.br
.ti -1c
.RI "void \fBsetPrecentTimeAnchorPoint\fP (double precentTimeAnchor)"
.br
.ti -1c
.RI "double \fBgetProbAnchorPoint\fP () const"
.br
.ti -1c
.RI "void \fBsetProbAnchorPoint\fP (double precentTimeAnchor)"
.br
.ti -1c
.RI "const string \fBtoString\fP ()"
.br
.ti -1c
.RI "void \fBsetAngleDistribution\fP (\fBDistribution\fP *distr)"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBgetAngleDistribution\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "vector< \fBHomeWorkLocation\fP > \fBm_homeLocations\fP"
.br
.ti -1c
.RI "vector< \fBHomeWorkLocation\fP > \fBm_workLocations\fP"
.br
.ti -1c
.RI "vector< \fBHomeWorkLocation\fP > \fBm_anchorLocations\fP"
.br
.ti -1c
.RI "double \fBm_precentTimeHome\fP"
.br
.ti -1c
.RI "double \fBm_precentTimeWork\fP"
.br
.ti -1c
.RI "double \fBm_precentTimeAnchor\fP"
.br
.ti -1c
.RI "double \fBm_precentTimeTravel\fP"
.br
.ti -1c
.RI "double \fBm_probAnchorPoint\fP"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBm_angleDistribution\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HomeWorkScenario::HomeWorkScenario ()"

.SS "virtual HomeWorkScenario::~HomeWorkScenario ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void HomeWorkScenario::addAnchorLocation (\fBHomeWorkLocation\fP h)"

.SS "void HomeWorkScenario::addHomeLocation (\fBHomeWorkLocation\fP h)"

.SS "void HomeWorkScenario::addWorkLocation (\fBHomeWorkLocation\fP h)"

.SS "vector<\fBHomeWorkLocation\fP> HomeWorkScenario::getAnchorLocations () const"

.SS "\fBDistribution\fP* HomeWorkScenario::getAngleDistribution ()"

.SS "vector<\fBHomeWorkLocation\fP> HomeWorkScenario::getHomeLocations () const"

.SS "double HomeWorkScenario::getPrecentTimeAnchorPoint () const"

.SS "double HomeWorkScenario::getPrecentTimeHome () const"

.SS "double HomeWorkScenario::getPrecentTimeTravel () const"

.SS "double HomeWorkScenario::getPrecentTimeWork () const"

.SS "double HomeWorkScenario::getProbAnchorPoint () const"

.SS "vector<\fBHomeWorkLocation\fP> HomeWorkScenario::getWorkLocations () const"

.SS "void HomeWorkScenario::setAngleDistribution (\fBDistribution\fP * distr)"

.SS "void HomeWorkScenario::setPrecentTimeAnchorPoint (double precentTimeAnchor)"

.SS "void HomeWorkScenario::setPrecentTimeHome (double precentTimeHome)"

.SS "void HomeWorkScenario::setPrecentTimeTravel (double precentTimetravel)"

.SS "void HomeWorkScenario::setPrecentTimeWork (double precentTimeWork)"

.SS "void HomeWorkScenario::setProbAnchorPoint (double precentTimeAnchor)"

.SS "const string HomeWorkScenario::toString ()"

.SH "Member Data Documentation"
.PP 
.SS "vector<\fBHomeWorkLocation\fP> HomeWorkScenario::m_anchorLocations\fC [private]\fP"

.SS "\fBDistribution\fP* HomeWorkScenario::m_angleDistribution\fC [private]\fP"

.SS "vector<\fBHomeWorkLocation\fP> HomeWorkScenario::m_homeLocations\fC [private]\fP"

.SS "double HomeWorkScenario::m_precentTimeAnchor\fC [private]\fP"

.SS "double HomeWorkScenario::m_precentTimeHome\fC [private]\fP"

.SS "double HomeWorkScenario::m_precentTimeTravel\fC [private]\fP"

.SS "double HomeWorkScenario::m_precentTimeWork\fC [private]\fP"

.SS "double HomeWorkScenario::m_probAnchorPoint\fC [private]\fP"

.SS "vector<\fBHomeWorkLocation\fP> HomeWorkScenario::m_workLocations\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
