.TH "ImmovableAgent" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImmovableAgent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImmovableAgent\&.h>\fP
.PP
Inherits \fBLocatableAgent\fP\&.
.PP
Inherited by \fBAntenna\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImmovableAgent\fP (const \fBMap\fP *m, const unsigned long id, Point *initialPosition, const \fBClock\fP *clock)"
.br
.ti -1c
.RI "virtual \fB~ImmovableAgent\fP ()"
.br
.ti -1c
.RI "const string \fBtoString\fP (bool detailed=false) const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a class that represents an agent which has a fixed location on the map\&. The only subclass of it is \fBAntenna\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImmovableAgent::ImmovableAgent (const \fBMap\fP * m, const unsigned long id, Point * initialPosition, const \fBClock\fP * clock)\fC [explicit]\fP"
Constructor of the class\&. It builds an \fBImmovableAgent\fP object with the parameters provided by the user\&. 
.PP
\fBParameters\fP
.RS 4
\fIm\fP a pointer to a \fBMap\fP object used for a simulation\&. 
.br
\fIid\fP the id of this object\&. 
.br
\fIinitialPosition\fP the initial location on map\&. 
.br
\fIclock\fP a pointer to a \fBClock\fP object used for a simulation\&. 
.RE
.PP

.SS "virtual ImmovableAgent::~ImmovableAgent ()\fC [virtual]\fP"
Default destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "const string ImmovableAgent::toString (bool detailed = \fCfalse\fP) const\fC [override]\fP, \fC [virtual]\fP"
Builds a string with the most relevant or all information of the class\&. It is useful to output the description of concrete agents to the console or to a file\&. Depending on the value of the \fCdetailed\fP parameter, the string can contain only the values of the the most important members (\fCdetailed = false\fP) or all members of the class\&. 
.PP
\fBParameters\fP
.RS 4
\fIdetailed\fP if true, the string will contain the values of all members/parameters of the agent, otherwise only the most important ones are written to the output string\&. Each derived class will decide which are the most important members\&. 
.RE
.PP
\fBReturns\fP
.RS 4
a string object containing the most important or all parameters/members of the agent\&. 
.RE
.PP

.PP
Implements \fBAgent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
