.TH "LevyFlightDisplacement" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevyFlightDisplacement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevyFlightDisplacement\&.h>\fP
.PP
Inherits \fBDisplace\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevyFlightDisplacement\fP (\fBSimulationConfiguration\fP *simConfig, double speed)"
.br
.ti -1c
.RI "virtual Point * \fBgenerateNewLocation\fP (Point *p) override"
.br
.ti -1c
.RI "virtual \fB~LevyFlightDisplacement\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual Point * \fBcomputeNewLocation\fP (Point *initLocation, double theta) override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBLevyFlightScenario\fP * \fBm_levyFlightScenario\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is part of the Strategy design pattern used to implement the displacement of persons on the map\&. It implements the Levy flights, overriding the \fBgenerateNewLocation()\fP method from its superclass, \fBDisplace\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LevyFlightDisplacement::LevyFlightDisplacement (\fBSimulationConfiguration\fP * simConfig, double speed)"
Constructor of the class\&. It only passes the arguments to the superclass, \fBDisplace\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIspeed\fP the speed of displacement\&. 
.RE
.PP

.SS "virtual LevyFlightDisplacement::~LevyFlightDisplacement ()\fC [virtual]\fP"
Destructor\&. Does nothing\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual Point* LevyFlightDisplacement::computeNewLocation (Point * initLocation, double theta)\fC [override]\fP, \fC [private]\fP, \fC [virtual]\fP"

.SS "virtual Point* LevyFlightDisplacement::generateNewLocation (Point * p)\fC [override]\fP, \fC [virtual]\fP"
Implements the Levy flight behavior\&. It takes a pointer to the current location, generates a uniformly distributed value between 0 and 2*PI as the angle of displacement and computes the length of the step in this direction using the speed and the time duration of a simulation step\&. To simulate a Levy flight, the value of the speed is generated at each time instant from a Levy distribution\&. If the new location is outside the map, it tries 10 times to generate another location\&. If after 10 trials the position is still outside the map returns the current location, i\&.e\&. the object will stay in the same location until the next simulation step\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP a pointer to the current location\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the new location 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBLevyFlightScenario\fP* LevyFlightDisplacement::m_levyFlightScenario\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
