.TH "LocatableAgent" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocatableAgent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LocatableAgent\&.h>\fP
.PP
Inherits \fBAgent\fP\&.
.PP
Inherited by \fBImmovableAgent\fP, and \fBMovableAgent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocatableAgent\fP (const \fBMap\fP *m, const unsigned long id, Point *initLocation, const \fBClock\fP *clock)"
.br
.ti -1c
.RI "virtual \fB~LocatableAgent\fP ()"
.br
.ti -1c
.RI "const string \fBtoString\fP () const override"
.br
.ti -1c
.RI "virtual Point * \fBgetLocation\fP () const"
.br
.ti -1c
.RI "virtual void \fBsetLocation\fP (Point *location)"
.br
.ti -1c
.RI "const string \fBdumpLocation\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Point * \fBm_location\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class extends the \fBAgent\fP class and defines an object with a location on a map\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LocatableAgent::LocatableAgent (const \fBMap\fP * m, const unsigned long id, Point * initLocation, const \fBClock\fP * clock)\fC [explicit]\fP"
Constructor of the class\&. Builds an object that has a location on the map of the simulation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP a pointer to a \fBMap\fP object used in this simulation\&. 
.br
\fIid\fP the id of the object\&. 
.br
\fIinitLocation\fP the initial location of the object\&. 
.br
\fIclock\fP a pointer to a \fBClock\fP object used in this simulation\&. 
.RE
.PP

.SS "virtual LocatableAgent::~LocatableAgent ()\fC [virtual]\fP"
Destructor 
.SH "Member Function Documentation"
.PP 
.SS "const string LocatableAgent::dumpLocation ()"
Builds a human readable string representation of the location 
.PP
\fBReturns:\fP
.RS 4
a human readable string representation of the location 
.RE
.PP

.SS "virtual Point* LocatableAgent::getLocation () const\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the location on the map as a pointer to a Point object\&. 
.RE
.PP

.SS "virtual void LocatableAgent::setLocation (Point * location)\fC [virtual]\fP"
Sets the location of the agent on the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlocation\fP the location of the agent on the map passed as a pointer to a Point object\&. 
.RE
.PP

.PP
Reimplemented in \fBPerson\fP, and \fBHoldableAgent\fP\&.
.SS "const string LocatableAgent::toString () const\fC [override]\fP, \fC [virtual]\fP"
Builds a human readable string representation of this class useful to output it to a file or on the screen\&. 
.PP
\fBReturns:\fP
.RS 4
a string representation of this class\&. 
.RE
.PP

.PP
Implements \fBAgent\fP\&.
.PP
Reimplemented in \fBMobilePhone\fP, \fBPerson\fP, \fBMovableAgent\fP, and \fBTablet\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Point* LocatableAgent::m_location\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
