.TH "Map" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.h>\fP
.PP
Inherited by \fBWKTMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Map\fP ()"
.br
.ti -1c
.RI "virtual Geometry * \fBgetBoundary\fP () const =0"
.br
.ti -1c
.RI "virtual Geometry * \fBgetEnvelope\fP () const =0"
.br
.ti -1c
.RI "virtual const GeometryFactory::Ptr & \fBgetGlobalFactory\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBaddGrid\fP (double dimTileX, double dimTileY)"
.br
.ti -1c
.RI "virtual unsigned long \fBgetNoTilesX\fP () const"
.br
.ti -1c
.RI "virtual unsigned long \fBgetNoTilesY\fP () const"
.br
.ti -1c
.RI "virtual double \fBgetXTileDim\fP () const"
.br
.ti -1c
.RI "virtual double \fBgetYTileDim\fP () const"
.br
.ti -1c
.RI "virtual double \fBgetXOrigin\fP () const"
.br
.ti -1c
.RI "virtual double \fBgetYOrigin\fP () const"
.br
.ti -1c
.RI "virtual const unsigned long \fBgetNoTiles\fP () const"
.br
.ti -1c
.RI "virtual Coordinate \fBgetTileCenter\fP (unsigned long tileIndex) const"
.br
.ti -1c
.RI "virtual unsigned long \fBgetTileNo\fP (const Point *p) const"
.br
.ti -1c
.RI "virtual unsigned long \fBgetTileNo\fP (double x, double y) const"
.br
.ti -1c
.RI "virtual void \fBdumpGrid\fP (const string &gridFileName) const"
.br
.ti -1c
.RI "virtual Coordinate * \fBgetTileCenters\fP () const"
.br
.ti -1c
.RI "virtual bool \fBhasGrid\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMap\fP (string mapFileName)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBGrid\fP * \fBm_grid\fP"
.br
.ti -1c
.RI "string \fBm_mapFileName\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Map::~Map ()\fC [virtual]\fP"

.SS "Map::Map (string mapFileName)\fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Map::addGrid (double dimTileX, double dimTileY)\fC [virtual]\fP"

.SS "virtual void Map::dumpGrid (const string & gridFileName) const\fC [virtual]\fP"

.SS "virtual Geometry* Map::getBoundary () const\fC [pure virtual]\fP"

.PP
Implemented in \fBWKTMap\fP\&.
.SS "virtual Geometry* Map::getEnvelope () const\fC [pure virtual]\fP"

.PP
Implemented in \fBWKTMap\fP\&.
.SS "virtual const GeometryFactory::Ptr& Map::getGlobalFactory () const\fC [pure virtual]\fP"

.PP
Implemented in \fBWKTMap\fP\&.
.SS "virtual const unsigned long Map::getNoTiles () const\fC [virtual]\fP"

.SS "virtual unsigned long Map::getNoTilesX () const\fC [virtual]\fP"

.SS "virtual unsigned long Map::getNoTilesY () const\fC [virtual]\fP"

.SS "virtual Coordinate Map::getTileCenter (unsigned long tileIndex) const\fC [virtual]\fP"

.SS "virtual Coordinate* Map::getTileCenters () const\fC [virtual]\fP"

.SS "virtual unsigned long Map::getTileNo (const Point * p) const\fC [virtual]\fP"

.SS "virtual unsigned long Map::getTileNo (double x, double y) const\fC [virtual]\fP"

.SS "virtual double Map::getXOrigin () const\fC [virtual]\fP"

.SS "virtual double Map::getXTileDim () const\fC [virtual]\fP"

.SS "virtual double Map::getYOrigin () const\fC [virtual]\fP"

.SS "virtual double Map::getYTileDim () const\fC [virtual]\fP"

.SS "virtual bool Map::hasGrid () const\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBGrid\fP* Map::m_grid\fC [protected]\fP"

.SS "string Map::m_mapFileName\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
