.TH "include/agent/MobilePhone.h" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/agent/MobilePhone.h
.SH SYNOPSIS
.br
.PP
\fC#include <agent/HoldableAgent\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMobilePhone\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
