.TH "include/MovementType.h" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/MovementType.h
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMovementType\fP { \fBMovementType::RANDOM_WALK_CLOSED_MAP\fP, \fBMovementType::RANDOM_WALK_CLOSED_MAP_WITH_DRIFT\fP, \fBMovementType::LEVY_FLIGHT\fP, \fBMovementType::UNKNOWN\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMovementType\fP\fC [strong]\fP"
An enum class that enumerates the types of the methods used to move the people on the map\&. RANDOM_WALK_CLOSED_MAP - the agent moves randomly inside the map boundary\&. The direction is generated as a random value at each time step and the step length is computed multiplying the speed with the time interval\&. RANDOM_WALK_CLOSED_MAP_WITH_DRIFT: the agent moves in a preferential direction\&. There are two constants defining these directions: SIM_TREND_ANGLE_1 and SIM_TREND_ANGLE_2 (3PI/4 and 5PI/4)\&. The actual direction is generated as a normally distributed random value with means equals to these constants and sad = 0\&.1\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRANDOM_WALK_CLOSED_MAP \fP\fP
.TP
\fB\fIRANDOM_WALK_CLOSED_MAP_WITH_DRIFT \fP\fP
.TP
\fB\fILEVY_FLIGHT \fP\fP
.TP
\fB\fIUNKNOWN \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
