.TH "Person" 3 "Wed May 19 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Person\&.h>\fP
.PP
Inherits \fBMovableAgent\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGender\fP { \fBMALE\fP, \fBFEMALE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class represents a person that can have 0, 1 or 2 mobile phone(s)\&. During the simulation, the person move around the map, carrying his/her mobile device(s)\&. At every time step, a new location is computed according to a movement strategy\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPerson::Gender\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMALE \fP\fP
.TP
\fB\fIFEMALE \fP\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
