.TH "PersonConfiguration" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PersonConfiguration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PersonConfiguration\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPersonConfiguration\fP ()"
.br
.ti -1c
.RI "virtual \fB~PersonConfiguration\fP ()"
.br
.ti -1c
.RI "int \fBgetAge\fP () const"
.br
.ti -1c
.RI "void \fBsetAge\fP (int age)"
.br
.ti -1c
.RI "\fBPerson::Gender\fP \fBgetGender\fP () const"
.br
.ti -1c
.RI "void \fBsetGender\fP (\fBPerson::Gender\fP gender)"
.br
.ti -1c
.RI "shared_ptr< \fBDistribution\fP > \fBgetIntervalBetweenStaysDistribution\fP () const"
.br
.ti -1c
.RI "void \fBsetIntervalBetweenStaysDistribution\fP (shared_ptr< \fBDistribution\fP > intervalBetweenStaysDistribution)"
.br
.ti -1c
.RI "double \fBgetSpeed\fP () const"
.br
.ti -1c
.RI "void \fBsetSpeed\fP (double speed)"
.br
.ti -1c
.RI "shared_ptr< \fBDistribution\fP > \fBgetTimeStayDistribution\fP () const"
.br
.ti -1c
.RI "void \fBsetTimeStayDistribution\fP (shared_ptr< \fBDistribution\fP > timeStayDistribution)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBm_speed\fP"
.br
.ti -1c
.RI "int \fBm_age\fP"
.br
.ti -1c
.RI "\fBPerson::Gender\fP \fBm_gender\fP"
.br
.ti -1c
.RI "shared_ptr< \fBDistribution\fP > \fBm_timeStayDistribution\fP"
.br
.ti -1c
.RI "shared_ptr< \fBDistribution\fP > \fBm_intervalBetweenStaysDistribution\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PersonConfiguration::PersonConfiguration ()"

.SS "virtual PersonConfiguration::~PersonConfiguration ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int PersonConfiguration::getAge () const"

.SS "\fBPerson::Gender\fP PersonConfiguration::getGender () const"

.SS "shared_ptr<\fBDistribution\fP> PersonConfiguration::getIntervalBetweenStaysDistribution () const"

.SS "double PersonConfiguration::getSpeed () const"

.SS "shared_ptr<\fBDistribution\fP> PersonConfiguration::getTimeStayDistribution () const"

.SS "void PersonConfiguration::setAge (int age)"

.SS "void PersonConfiguration::setGender (\fBPerson::Gender\fP gender)"

.SS "void PersonConfiguration::setIntervalBetweenStaysDistribution (shared_ptr< \fBDistribution\fP > intervalBetweenStaysDistribution)"

.SS "void PersonConfiguration::setSpeed (double speed)"

.SS "void PersonConfiguration::setTimeStayDistribution (shared_ptr< \fBDistribution\fP > timeStayDistribution)"

.SH "Member Data Documentation"
.PP 
.SS "int PersonConfiguration::m_age\fC [private]\fP"

.SS "\fBPerson::Gender\fP PersonConfiguration::m_gender\fC [private]\fP"

.SS "shared_ptr<\fBDistribution\fP> PersonConfiguration::m_intervalBetweenStaysDistribution\fC [private]\fP"

.SS "double PersonConfiguration::m_speed\fC [private]\fP"

.SS "shared_ptr<\fBDistribution\fP> PersonConfiguration::m_timeStayDistribution\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
