.TH "PostLocProb" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostLocProb
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UnifPriorPostLocProb\&.h>\fP
.PP
Inherited by \fBNetPriorPostLocProb\fP, and \fBUnifPriorPostLocProb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPostLocProb\fP (const \fBMap\fP *m, \fBClock\fP *clk, \fBAgentsCollection\fP *agents, map< const unsigned long, const string > probFiles)"
.br
.ti -1c
.RI "virtual \fB~PostLocProb\fP ()"
.br
.ti -1c
.RI "virtual void \fBcomputeProbabilities\fP (std::map< unsigned long, vector< \fBAntennaInfo\fP >> data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements a Strategy design pattern\&. It acts as an interface to different algorithms for posterior location probabilities computation\&.
.PP
This class is part of the Strategy design pattern used to compute the posterior location probabilities\&. It implements the computation of the posterior location probabilities starting from the prior probabilities given by the network, overriding the prob() method from its superclass,
.PP
This class is part of the Strategy design pattern used to compute the posterior location probabilities\&. It implements the computation of the posterior location probabilities starting from the uniform prior probabilities, overriding the prob() method from its superclass, 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PostLocProb::PostLocProb (const \fBMap\fP * m, \fBClock\fP * clk, \fBAgentsCollection\fP * agents, map< const unsigned long, const string > probFiles)"
Constructor of the class\&. It initializes the members according to the values given as parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIm\fP a pointer to the \fBMap\fP object of the simulation\&. 
.br
\fIclk\fP a pointer to the \fBClock\fP object of the simulation\&. 
.br
\fIagents\fP a pointer to the \fBAgentsCollection\fP object (it contains all the agents in a simulation)\&. 
.br
\fIprobFiles\fP a map object containing the name of the files where the probabilities are saved, one file per MNO\&. 
.RE
.PP

.SS "virtual PostLocProb::~PostLocProb ()\fC [virtual]\fP"
Default destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void PostLocProb::computeProbabilities (std::map< unsigned long, vector< \fBAntennaInfo\fP >> data)\fC [virtual]\fP"
Computes the posterior location probabilities\&. It iterates over all time instants and mobile phone and calls the prob() pure virtual function which implements the actual algorithm for the location probabilities\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP a vector with the network events\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
