.TH "RandomWalkDisplacement" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomWalkDisplacement
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RandomWalkDisplacement\&.h>\fP
.PP
Inherits \fBDisplace\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomWalkDisplacement\fP (\fBSimulationConfiguration\fP *simConfig, double speed)"
.br
.ti -1c
.RI "virtual Point * \fBgenerateNewLocation\fP (Point *p) override"
.br
.ti -1c
.RI "virtual \fB~RandomWalkDisplacement\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is part of the Strategy design pattern used to implement the displacement of persons on the map\&. It implements the pure random walk behaviour, overriding the \fBgenerateNewLocation()\fP method from its superclass, \fBDisplace\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RandomWalkDisplacement::RandomWalkDisplacement (\fBSimulationConfiguration\fP * simConfig, double speed)"
Constructor of the class\&. It only passes the arguments to the superclass, \fBDisplace\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIspeed\fP the speed of displacement\&. 
.RE
.PP

.SS "virtual RandomWalkDisplacement::~RandomWalkDisplacement ()\fC [virtual]\fP"
Destructor\&. It does nothing\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual Point* RandomWalkDisplacement::generateNewLocation (Point * p)\fC [override]\fP, \fC [virtual]\fP"
Implements the random walk behaviour\&. It takes a pointer to the current location, generates a uniformly distributed value between 0 and 2 PI as the angle of displacement and computes the length of the step in this direction using the speed and the time duration of a simulation step\&. If the new location is outside the map, it returns the current location, i\&.e\&. the object will stay in the same location until the next simulation step\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP a pointer to the current location\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the new location 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
