.TH "RandomWalkDriftScenario" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomWalkDriftScenario
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RandomWalkDriftScenario\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomWalkDriftScenario\fP ()"
.br
.ti -1c
.RI "virtual \fB~RandomWalkDriftScenario\fP ()"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBgetTrendAngle1Distribution\fP () const"
.br
.ti -1c
.RI "void \fBsetTrendAngle1Distribution\fP (\fBDistribution\fP *trendAngle1)"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBgetTrendAngle2Distribution\fP () const"
.br
.ti -1c
.RI "void \fBsetTrendAngle2Distribution\fP (\fBDistribution\fP *trendAngle2)"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBgetReturnAngleDistribution\fP () const"
.br
.ti -1c
.RI "void \fBsetReturnAngleDistribution\fP (\fBDistribution\fP *returnAngleDistribution)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDistribution\fP * \fBm_trendAngle1Distribution\fP"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBm_trendAngle2Distribution\fP"
.br
.ti -1c
.RI "\fBDistribution\fP * \fBm_returnAngleDistribution\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RandomWalkDriftScenario::RandomWalkDriftScenario ()"

.SS "virtual RandomWalkDriftScenario::~RandomWalkDriftScenario ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBDistribution\fP* RandomWalkDriftScenario::getReturnAngleDistribution () const"

.SS "\fBDistribution\fP* RandomWalkDriftScenario::getTrendAngle1Distribution () const"

.SS "\fBDistribution\fP* RandomWalkDriftScenario::getTrendAngle2Distribution () const"

.SS "void RandomWalkDriftScenario::setReturnAngleDistribution (\fBDistribution\fP * returnAngleDistribution)"

.SS "void RandomWalkDriftScenario::setTrendAngle1Distribution (\fBDistribution\fP * trendAngle1)"

.SS "void RandomWalkDriftScenario::setTrendAngle2Distribution (\fBDistribution\fP * trendAngle2)"

.SH "Member Data Documentation"
.PP 
.SS "\fBDistribution\fP* RandomWalkDriftScenario::m_returnAngleDistribution\fC [private]\fP"

.SS "\fBDistribution\fP* RandomWalkDriftScenario::m_trendAngle1Distribution\fC [private]\fP"

.SS "\fBDistribution\fP* RandomWalkDriftScenario::m_trendAngle2Distribution\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
