.TH "Row" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Row
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSVparser\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRow\fP (const vector< string > &header)"
.br
.ti -1c
.RI "\fB~Row\fP (void)"
.br
.ti -1c
.RI "unsigned int \fBsize\fP (void) const"
.br
.ti -1c
.RI "void \fBpush\fP (const string &value)"
.br
.ti -1c
.RI "bool \fBset\fP (const string &key, const string &value)"
.br
.ti -1c
.RI "template<typename T > const T \fBgetValue\fP (unsigned int pos) const"
.br
.ti -1c
.RI "const string \fBoperator[]\fP (unsigned int i) const"
.br
.ti -1c
.RI "const string \fBoperator[]\fP (const string &valueName) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const vector< string > \fB_header\fP"
.br
.ti -1c
.RI "vector< string > \fB_values\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBRow\fP &row)"
.br
.ti -1c
.RI "ofstream & \fBoperator<<\fP (ofstream &os, const \fBRow\fP &row)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to represent a line from a \&.csv file\&. It is a container of the values from a line of text\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Row::Row (const vector< string > & header)"
Constructor\&. It takes a a line of text representing the header of the csv file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIheader\fP the header line 
.RE
.PP

.SS "Row::~Row (void)"
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const T Row::getValue (unsigned int pos) const\fC [inline]\fP"
Returns the value of an element from a row 
.PP
\fBParameters:\fP
.RS 4
\fIpos\fP the number of the element in row 
.RE
.PP
\fBReturns:\fP
.RS 4
the value 
.RE
.PP

.SS "const string Row::operator[] (unsigned int i) const"
Overloaded operator 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP the position of the value that we want to extract 
.RE
.PP
\fBReturns:\fP
.RS 4
the value from position i 
.RE
.PP

.SS "const string Row::operator[] (const string & valueName) const"
Overloaded operator 
.PP
\fBParameters:\fP
.RS 4
\fIvalueName\fP the name of the column from which we want to extract a the value 
.RE
.PP
\fBReturns:\fP
.RS 4
the value from the column specified by its name 
.RE
.PP

.SS "void Row::push (const string & value)"
Add a new value on a row 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP to be added 
.RE
.PP

.SS "bool Row::set (const string & key, const string & value)"
Sets the value of a specific element in a row\&. The element is specified by the column name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP the name of the column (given in the header of the file) 
.br
\fIvalue\fP the value to be set 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "unsigned int Row::size (void) const"
Returns the number of values on a row\&. 
.PP
\fBReturns:\fP
.RS 4
the number of values on a row\&. 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBRow\fP & row)\fC [friend]\fP"
Overloaded operator outputs the content of a row in a stream 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP the stream where we want to send the content of the row\&. 
.br
\fIrow\fP the row that we want to output 
.RE
.PP
\fBReturns:\fP
.RS 4
the same output stream 
.RE
.PP

.SS "ofstream& operator<< (ofstream & os, const \fBRow\fP & row)\fC [friend]\fP"
Overloaded operator outputs the content of a row in a file stream 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP the file stream where we want to send the content of the row\&. 
.br
\fIrow\fP the row that we want to output 
.RE
.PP
\fBReturns:\fP
.RS 4
the same output file stream 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "const vector<string> Row::_header\fC [private]\fP"

.SS "vector<string> Row::_values\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
