.TH "SimConfigParser" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimConfigParser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimConfigParser\&.h>\fP
.PP
Inherits \fBConfigParser\fP\&.
.SH "Detailed Description"
.PP 
This class parses the simulation configuration file, given in the command line with the prefix -s\&. It provides getters for all fields parsed from the xml file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
