.TH "SimException" 3 "Wed Aug 26 2020" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimException\&.h>\fP
.PP
Inherits \fBexception\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimException\fP (const char *\fBmsg\fP)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.ti -1c
.RI "virtual \fB~SimException\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char * \fBmsg\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SimException::SimException (const char * msg)"

.SS "virtual SimException::~SimException ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char* SimException::what () const\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const char* SimException::msg\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
