.TH "include/Tablet.h" 3 "Wed Oct 30 2019" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Tablet.h
.SH SYNOPSIS
.br
.PP
\fC#include <HoldableAgent\&.h>\fP
.br
\fC#include <MovementType\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTablet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
