.TH "TruncatedNormalAgeDistribution" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TruncatedNormalAgeDistribution
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TruncatedNormalAgeDistribution\&.h>\fP
.PP
Inherits \fBAgeDistribution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTruncatedNormalAgeDistribution\fP (int minAge, int maxAge, double meanAge, double sd)"
.br
.ti -1c
.RI "virtual \fB~TruncatedNormalAgeDistribution\fP ()"
.br
.ti -1c
.RI "double \fBgetMean\fP () const"
.br
.ti -1c
.RI "void \fBsetMean\fP (double mean)"
.br
.ti -1c
.RI "double \fBgetSd\fP () const"
.br
.ti -1c
.RI "void \fBsetSd\fP (double sd)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBm_mean\fP"
.br
.ti -1c
.RI "double \fBm_sd\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TruncatedNormalAgeDistribution::TruncatedNormalAgeDistribution (int minAge, int maxAge, double meanAge, double sd)"
Constructor of the class\&. It sets the members according to the values given as parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIminAge\fP the minimum value of the truncated normal age distribution\&. 
.br
\fImaxAge\fP the maximum value of the truncated normal age distribution\&. 
.br
\fImeanAge\fP the mean value of the truncated normal age distribution\&. 
.br
\fIsd\fP the standard deviation value of the standard deviation\&. 
.RE
.PP

.SS "virtual TruncatedNormalAgeDistribution::~TruncatedNormalAgeDistribution ()\fC [virtual]\fP"
Default destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "double TruncatedNormalAgeDistribution::getMean () const"
Returns the mean of the age distribution\&. 
.PP
\fBReturns\fP
.RS 4
the mean value of the age distribution\&. 
.RE
.PP

.SS "double TruncatedNormalAgeDistribution::getSd () const"
Returns the standard deviation of the age distribution\&. 
.PP
\fBReturns\fP
.RS 4
the standard deviation of the age distribution\&. 
.RE
.PP

.SS "void TruncatedNormalAgeDistribution::setMean (double mean)"
Sets the mean value of the age distribution\&. 
.PP
\fBParameters\fP
.RS 4
\fImean\fP the mean value of the age distribution\&. 
.RE
.PP

.SS "void TruncatedNormalAgeDistribution::setSd (double sd)"
Sets the value of the standard deviation of the age distribution\&. 
.PP
\fBParameters\fP
.RS 4
\fIsd\fP the standard deviation of the age distribution\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double TruncatedNormalAgeDistribution::m_mean\fC [private]\fP"

.SS "double TruncatedNormalAgeDistribution::m_sd\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
