.TH "UniformAgeDistribution" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniformAgeDistribution
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UniformAgeDistribution\&.h>\fP
.PP
Inherits \fBAgeDistribution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniformAgeDistribution\fP (int min_age, int max_age)"
.br
.ti -1c
.RI "virtual \fB~UniformAgeDistribution\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UniformAgeDistribution::UniformAgeDistribution (int min_age, int max_age)"
Constructor of the class\&. It sets the members according to the values given as parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fImin_age\fP the minimum value for the age distribution\&. 
.br
\fImax_age\fP the maximum value for the age distribution\&. 
.RE
.PP

.SS "virtual UniformAgeDistribution::~UniformAgeDistribution ()\fC [virtual]\fP"
Default destructor\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
