.TH "UnifPriorPostLocProb" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnifPriorPostLocProb
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UnifPriorPostLocProb\&.h>\fP
.PP
Inherits \fBPostLocProb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnifPriorPostLocProb\fP (const \fBMap\fP *m, \fBClock\fP *clk, \fBAgentsCollection\fP *agents, map< const unsigned long, const string > probFiles)"
.br
.ti -1c
.RI "virtual \fB~UnifPriorPostLocProb\fP ()"
.br
.ti -1c
.RI "virtual vector< double > \fBprob\fP (unsigned long t, \fBMobilePhone\fP *m, vector< \fBAntennaInfo\fP > &data, pair< \fBum_iterator\fP, \fBum_iterator\fP > it) override"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UnifPriorPostLocProb::UnifPriorPostLocProb (const \fBMap\fP * m, \fBClock\fP * clk, \fBAgentsCollection\fP * agents, map< const unsigned long, const string > probFiles)"
Constructor of the class\&. It sets the members according to the values given as parameters\&. 
.PP
\fBParameters\fP
.RS 4
\fIm\fP a pointer to the \fBMap\fP object of the simulation\&. 
.br
\fIclk\fP a pointer to the \fBClock\fP object of the simulation\&. 
.br
\fIagents\fP a pointer to the \fBAgentsCollection\fP object\&. 
.br
\fIprobFiles\fP the name of the files where the posterior probabilities are saved (one file per MNO)\&. 
.RE
.PP

.SS "virtual UnifPriorPostLocProb::~UnifPriorPostLocProb ()\fC [virtual]\fP"
Default destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual vector<double> UnifPriorPostLocProb::prob (unsigned long t, \fBMobilePhone\fP * m, vector< \fBAntennaInfo\fP > & data, pair< \fBum_iterator\fP, \fBum_iterator\fP > it)\fC [override]\fP, \fC [virtual]\fP"
Implements the computation of the posterior location probabilities with the uniform priors\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP the time instant for which the probabilities are computed\&. 
.br
\fIm\fP a pointer to a \fBMobilePhone\fP object for which the probabilities are computed\&. 
.br
\fIdata\fP a vector with the network events\&. 
.br
\fIit\fP an iterator the the antenna's list\&. 
.RE
.PP
\fBReturns\fP
.RS 4
a vector with the posterior location probabilities for each time instant and mobile phone\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
