.TH "include/Utils.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Utils.h
.SH SYNOPSIS
.br
.PP
\fC#include <agent/AgentsCollection\&.h>\fP
.br
\fC#include <agent/MobilePhone\&.h>\fP
.br
\fC#include <events/EventType\&.h>\fP
.br
\fC#include <AntennaInfo\&.h>\fP
.br
\fC#include <geos/geom/Point\&.h>\fP
.br
\fC#include <PriorType\&.h>\fP
.br
\fC#include <NetworkType\&.h>\fP
.br
\fC#include <parsers/SimulationConfiguration\&.h>\fP
.br
\fC#include <RandomNumberGenerator\&.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <TinyXML2\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fButils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "vector< Point * > \fButils::generatePoints\fP (\fBSimulationConfiguration\fP *sc, unsigned long n, double percentHome)"
.br
.ti -1c
.RI "vector< Point * > \fButils::generateRandomPoints\fP (\fBSimulationConfiguration\fP *sc, unsigned long n, double percentHome)"
.br
.ti -1c
.RI "vector< Point * > \fButils::generateHomeWorkPoints\fP (\fBSimulationConfiguration\fP *sc, unsigned long n, double percentHome)"
.br
.ti -1c
.RI "void \fButils::generateHomeLocation\fP (\fBMap\fP *m, \fBHomeWorkLocation\fP hLoc, unsigned int npers, \fBRandomNumberGenerator\fP *random_gernerator, vector< Point * > &result)"
.br
.ti -1c
.RI "vector< Point * > \fButils::generateFixedPoints\fP (const \fBMap\fP *m, unsigned long n, \fBRandomNumberGenerator\fP *random_generator)"
.br
.ti -1c
.RI "double \fButils::r2d\fP (double x)"
.br
.ti -1c
.RI "double \fButils::d2r\fP (double x)"
.br
.ti -1c
.RI "XMLNode * \fButils::getNode\fP (XMLElement *el, const char *name)"
.br
.ti -1c
.RI "XMLElement * \fButils::getFirstChildElement\fP (XMLElement *el, const char *name) noexcept(false)"
.br
.ti -1c
.RI "double \fButils::getValue\fP (XMLElement *el, const char *name, double default_value)"
.br
.ti -1c
.RI "int \fButils::getValue\fP (XMLElement *el, const char *name, int default_value)"
.br
.ti -1c
.RI "unsigned long \fButils::getValue\fP (XMLElement *el, const char *name, unsigned long default_value)"
.br
.ti -1c
.RI "const char * \fButils::getValue\fP (XMLElement *el, const char *name, const char *default_value)"
.br
.ti -1c
.RI "double \fButils::getValue\fP (XMLElement *el, const char *name)"
.br
.ti -1c
.RI "\fBNetworkType\fP \fButils::getValue\fP (XMLElement *el, const char *name, \fBNetworkType\fP default_value)"
.br
.ti -1c
.RI "\fBEventType\fP \fButils::getValue\fP (XMLElement *el, const char *name, \fBEventType\fP default_value)"
.br
.ti -1c
.RI "double \fButils::inverseNormalCDF\fP (const double p, const double mu, const double sigma)"
.br
.ti -1c
.RI "string \fButils::toString\fP (\fBNetworkType\fP type)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fButils::PI\fP = std::atan(1\&.0) * 4"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
