.TH "include/map/WKTMap.h" 3 "Thu May 20 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/map/WKTMap.h
.SH SYNOPSIS
.br
.PP
\fC#include <geos/geom/GeometryFactory\&.h>\fP
.br
\fC#include 'map/Map\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWKTMap\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
