.TH "include/World.h" 3 "Wed May 12 2021" "Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/World.h
.SH SYNOPSIS
.br
.PP
\fC#include <agent/Antenna\&.h>\fP
.br
\fC#include <AntennaInfo\&.h>\fP
.br
\fC#include <events/EventFactory\&.h>\fP
.br
\fC#include <parsers/AntennaConfigParser\&.h>\fP
.br
\fC#include <parsers/PersonsConfigParser\&.h>\fP
.br
\fC#include <parsers/ProbabilitiesConfigParser\&.h>\fP
.br
\fC#include <parsers/SimConfigParser\&.h>\fP
.br
\fC#include <parsers/SimulationConfiguration\&.h>\fP
.br
\fC#include <RandomNumberGenerator\&.h>\fP
.br
\fC#include <PostLocProb\&.h>\fP
.br
\fC#include <PriorType\&.h>\fP
.br
\fC#include <map>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorld\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulator from the source code\&.
