/*
 * Copyright (C) 2019  Bogdan Oancea

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version and under the EUPL free software license version 1.0 or later.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/> and
 * <https://ec.europa.eu/info/european-union-public-licence_en>
 *
 * A data simulator for mobile phone network events
 *
 * AntennaInfo.h
 *
 *  Created on: May 16, 2019
 *      Author: Bogdan Oancea
 *      Email : bogdan.oancea@gmail.com
 */

#ifndef ANTENNAINFO_H_
#define ANTENNAINFO_H_

#include <string>
using namespace std;

/**
 * This class is used to encapsulate all the information about an event generated by an antenna: the timestamp, antennaId, event code,
 * the device id, the exact location of the event.
 *
 */
class AntennaInfo {
public:
	/**
	 * Constructor of the class, builds an object with the values of the fields provided as arguments.
	 * @param time the timestamp of the event.
	 * @param antennaId the id of the antenna that registered an event.
	 * @param event the event code.
	 * @param deviceId the id of the device that generated the event.
	 * @param x x coordinate of the device when the event was generated.
	 * @param y y coordinate of the device when the event was generated.
	 */
	AntennaInfo(const unsigned long time, const unsigned long antennaId,
			const unsigned long event, const unsigned long deviceId, const double x, const double y);
	/**
	 * @return the id of the antenna that registered the event.
	 */
	unsigned long getAntennaId() const;


	/**
	 *@return the id of the device that generated the event.
	 */
	unsigned long getDeviceId() const;

	/**
	 * @return the event code. It could take the following values: 0 - a device is connected to an antenna, 1 - a devices is
	 * disconnected from an antenna, 2 - a device is already connected to the antenna that registered the event,
	 * 3 - a device was detected in the coverage area of an antenna but the connection to the antenna failed (from different reasons).
	 */
	unsigned long getEventCode() const;

	/**
	 * @return the timestamp of the event.
	 */
	unsigned long getTime() const;

	/**
	 *
	 * @return x coordinate of the device that generated the event.
	 */
	double getX() const;

	/**
	 *
	 * @return y coordinate of the device that generated the event.
	 */
	double getY() const;

	/**
	 *
	 * @return a string representation of on object of this class.
	 */
	const string toString() const;

	/**
	 * Overloaded operator to compare to objects
	 * @param ai the other object to compare to.
	 * @return true if this object is less than ai, false otherwise. An object is less than another object if the
	 * timestamp value of the first object is lees than the timestamp of the second one.
	 */
	bool operator < (const AntennaInfo& ai) const;

private:
	unsigned long m_time;
	unsigned long m_antennaId;
	unsigned long m_eventCode;
	unsigned long m_deviceId;
	double m_x;
	double m_y;
};

#endif /* ANTENNAINFO_H_ */
