/*
 * Data simulator for mobile phone network events
 *
 * AntennaInfo.h
 *
 *  Created on: May 16, 2019
 *      Author: Bogdan Oancea
 */

#ifndef ANTENNAINFO_H_
#define ANTENNAINFO_H_

#include <string>
using namespace std;

/**
 * This class is used to encapsulate all the information about an event generated by an antenna: the timestamp, antennaId, event code,
 * device Id that generated the event and the exact position of the device
 *
 */
class AntennaInfo {
public:
	/**
	 * Constructor of the class, builds an object with the values of the fiedls provided as arguments.
	 * @param time the timestamp of the event
	 * @param antennaId the id of the antenna that registered an event
	 * @param event the event code
	 * @param deviceId the id of the device that generated the event
	 * @param x x coordinate of the device when the event was generated
	 * @param y y coordinate of the device when the event was generated
	 */
	AntennaInfo(unsigned long time, unsigned long antennaId,
			unsigned long event, unsigned long deviceId, double x, double y);
	/**
	 * @return the id of the antenna that registered an event.
	 */
	unsigned long getAntennaId() const;


	/**
	 *@return the id of the device that generated the event
	 */
	unsigned long getDeviceId() const;

	/**
	 * @return the event code
	 */
	unsigned long getEventCode() const;

	/**
	 * @return the timestamp of the event
	 */
	unsigned long getTime() const;

	/**
	 *
	 * @return x coordinate of the device that generated the event
	 */
	double getX() const;

	/**
	 *
	 * @return y coordinate of the device that generated the event
	 */
	double getY() const;

	/**
	 *
	 * @return a string representation of on object of this class
	 */
	string toString() const;

private:
	unsigned long m_time;
	unsigned long m_antennaId;
	unsigned long m_eventCode;
	unsigned long m_deviceId;
	double m_x;
	double m_y;
};

#endif /* ANTENNAINFO_H_ */
